// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	ColumnCreateOperation           OperationName = "ColumnCreate"
	ColumnDeleteOperation           OperationName = "ColumnDelete"
	ColumnUpdateOperation           OperationName = "ColumnUpdate"
	ExecuteOperation                OperationName = "Execute"
	ExecuteOptionsOperation         OperationName = "ExecuteOptions"
	GetHealthzOperation             OperationName = "GetHealthz"
	GetInfoOperation                OperationName = "GetInfo"
	GetLivezOperation               OperationName = "GetLivez"
	GetReadyzOperation              OperationName = "GetReadyz"
	GetSchemaOperation              OperationName = "GetSchema"
	GetStartupzOperation            OperationName = "GetStartupz"
	GetStatisticsOperation          OperationName = "GetStatistics"
	IndexCreateOperation            OperationName = "IndexCreate"
	IndexDeleteOperation            OperationName = "IndexDelete"
	QueryOperation                  OperationName = "Query"
	SchemaCompatibilityOperation    OperationName = "SchemaCompatibility"
	SchemaDiffOperation             OperationName = "SchemaDiff"
	SchemaMigrateOperation          OperationName = "SchemaMigrate"
	SchemaTransitionCancelOperation OperationName = "SchemaTransitionCancel"
	SchemaTransitionGetOperation    OperationName = "SchemaTransitionGet"
	SchemaTransitionListOperation   OperationName = "SchemaTransitionList"
	TableCreateOperation            OperationName = "TableCreate"
	TableDeleteOperation            OperationName = "TableDelete"
	TableListOperation              OperationName = "TableList"
	TableUpdateOperation            OperationName = "TableUpdate"
)
