//! The shipped specification must parse, validate, and emit deterministically.

#[test]
fn shipped_specification_compiles() {
    let source = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../protocol/storage.keyform"
    ))
    .expect("read the shipped specification");
    let spec = keyform::parse(&source).expect("shipped specification parses");
    keyform::validate(&spec).expect("shipped specification validates");

    let first = keyform::emit(&spec, &source);
    let second = keyform::emit(&spec, &source);
    assert_eq!(first, second, "emission is deterministic");
    let paths: Vec<&str> = first.iter().map(|(path, _)| path.as_str()).collect();
    assert_eq!(
        paths,
        [
            "src/engine/01_kv/manifest.rs",
            "src/engine/01_kv/keyspace.rs",
            "src/engine/01_kv/keys.rs",
            "src/engine/05_exec/key_describe.rs",
            "tests/storage_spec.rs",
            "home/public/schema/storage-keyspaces.json",
        ]
    );
    for (path, content) in &first {
        if !path.ends_with(".rs") {
            continue;
        }
        assert!(
            content.starts_with("// GENERATED by keyform"),
            "{path} lacks the generated header"
        );
    }
}
