// GENERATED by keyform from protocol/storage.keyform. Do not edit.
// Regenerate with `task generate:storage`.

//! Conformance suite binding the normative storage specification to the
//! implementation: authored byte vectors, declared laws over seeded
//! samples, and the keyspace registry.

use rad::engine::catalog::identity::{
    DefinitionGeneration, ExistenceGeneration, SchemaId, StorageGeneration, ValueGeneration,
    WriteProtocolGeneration,
};
use rad::engine::catalog::model::{Column, ScalarType, Table};
use rad::engine::lir::{Row, Value};
use sha2::{Digest, Sha256};

fn splitmix64(state: &mut u64) -> u64 {
    *state = state.wrapping_add(0x9e37_79b9_7f4a_7c15);
    let mut value = *state;
    value = (value ^ (value >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
    value = (value ^ (value >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
    value ^ (value >> 31)
}

fn generated_text(state: &mut u64) -> String {
    let length = (splitmix64(state) % 12) as usize;
    (0..length)
        .map(|_| match splitmix64(state) % 8 {
            0 => '\0',
            1 => '\u{1}',
            2 => 'é',
            3 => '🦀',
            _ => char::from(b'a' + (splitmix64(state) % 26) as u8),
        })
        .collect()
}

fn generated_scalar(state: &mut u64) -> Value {
    match splitmix64(state) % 6 {
        0 => Value::Null(ScalarType::Text),
        1 => Value::Bool(splitmix64(state) % 2 == 1),
        2 => Value::Int64(splitmix64(state) as i64),
        3 => {
            let value = f64::from_bits(splitmix64(state));
            Value::Float64(if value.is_finite() { value } else { 0.5 })
        }
        _ => Value::Text(generated_text(state)),
    }
}

/// Value identity under the codec contract: nulls match regardless of the
/// contextual scalar type, and floats compare by bit pattern after the
/// canonical `-0.0` to `+0.0` normalisation.
fn values_match(actual: &Value, expected: &Value) -> bool {
    match (actual, expected) {
        (Value::Null(_), Value::Null(_)) => true,
        (Value::Float64(actual), Value::Float64(expected)) => {
            let canonical = if *expected == 0.0 { 0.0 } else { *expected };
            actual.to_bits() == canonical.to_bits()
        }
        _ => actual == expected,
    }
}

/// Key encoding for one scalar, `None` for values the ordered key
/// layer cannot represent.
fn kv_encode(value: &Value) -> Option<Vec<u8>> {
    Some(match value {
        Value::Null(_) => rad::engine::kv::key_encoding::encode_null().to_vec(),
        Value::Bool(value) => rad::engine::kv::key_encoding::encode_bool(*value).to_vec(),
        Value::Int64(value) => rad::engine::kv::key_encoding::encode_i64(*value).to_vec(),
        Value::Float64(value) => rad::engine::kv::key_encoding::encode_f64(*value)?.to_vec(),
        Value::Text(value) => rad::engine::kv::key_encoding::encode_text(value),
    })
}

fn fuzz_rows_column(id: &str, schema_id: u32, name: &str, scalar_type: ScalarType) -> Column {
    Column {
        id: id.into(),
        schema_id: SchemaId::new(schema_id).expect("fixture schema IDs are positive"),
        name: name.into(),
        value_generation: ValueGeneration::ZERO,
        scalar_type,
        nullable: true,
        format: String::new(),
        insert_default: None,
        missing_value: None,
    }
}

fn fuzz_rows_table() -> Table {
    Table {
        id: "t1".into(),
        schema_id: SchemaId::new(1).expect("fixture schema IDs are positive"),
        name: "fuzz_rows".into(),
        definition_generation: DefinitionGeneration::ZERO,
        existence_generation: ExistenceGeneration::ZERO,
        write_protocol_generation: WriteProtocolGeneration::ZERO,
        storage_generation: StorageGeneration::INITIAL,
        columns: vec![
            fuzz_rows_column("c1", 1, "id", ScalarType::Text),
            fuzz_rows_column("c2", 2, "count", ScalarType::Int64),
            fuzz_rows_column("c3", 3, "ready", ScalarType::Bool),
            fuzz_rows_column("c4", 4, "score", ScalarType::Float64),
        ],
        primary_key: vec!["id".into()],
        indexes: Vec::new(),
        foreign_keys: Vec::new(),
        constraints: Vec::new(),
    }
}

#[test]
fn manifest_matches_the_normative_specification() {
    let text = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/protocol/storage.keyform"
    ))
    .expect("read the normative specification");
    let digest = Sha256::digest(&text);
    let mut hex = String::with_capacity(64);
    for byte in digest {
        hex.push_str(&format!("{byte:02x}"));
    }
    assert_eq!(
        hex,
        rad::engine::kv::manifest::STORAGE_SPEC_SHA256,
        "specification changed without regeneration; run `task generate:storage`"
    );
    assert_eq!(rad::engine::kv::manifest::STORAGE_FORMAT_NAME, "storage");
    assert_eq!(rad::engine::kv::manifest::STORAGE_FORMAT_VERSION, 1);
}

#[test]
fn uvarint_vectors() {
    // 0
    let bytes: &[u8] = &[0x00];
    let mut position = 0;
    assert_eq!(
        rad::engine::exec::codec::read_uvarint(bytes, &mut position)
            .expect("accept vector decodes"),
        0_u64
    );
    assert_eq!(position, bytes.len());
    let mut encoded = Vec::new();
    rad::engine::exec::codec::append_uvarint(&mut encoded, 0_u64);
    assert_eq!(encoded, bytes);
    // 127
    let bytes: &[u8] = &[0x7f];
    let mut position = 0;
    assert_eq!(
        rad::engine::exec::codec::read_uvarint(bytes, &mut position)
            .expect("accept vector decodes"),
        127_u64
    );
    assert_eq!(position, bytes.len());
    let mut encoded = Vec::new();
    rad::engine::exec::codec::append_uvarint(&mut encoded, 127_u64);
    assert_eq!(encoded, bytes);
    // 128
    let bytes: &[u8] = &[0x80, 0x01];
    let mut position = 0;
    assert_eq!(
        rad::engine::exec::codec::read_uvarint(bytes, &mut position)
            .expect("accept vector decodes"),
        128_u64
    );
    assert_eq!(position, bytes.len());
    let mut encoded = Vec::new();
    rad::engine::exec::codec::append_uvarint(&mut encoded, 128_u64);
    assert_eq!(encoded, bytes);
    // 16383
    let bytes: &[u8] = &[0xff, 0x7f];
    let mut position = 0;
    assert_eq!(
        rad::engine::exec::codec::read_uvarint(bytes, &mut position)
            .expect("accept vector decodes"),
        16383_u64
    );
    assert_eq!(position, bytes.len());
    let mut encoded = Vec::new();
    rad::engine::exec::codec::append_uvarint(&mut encoded, 16383_u64);
    assert_eq!(encoded, bytes);
    // 16384
    let bytes: &[u8] = &[0x80, 0x80, 0x01];
    let mut position = 0;
    assert_eq!(
        rad::engine::exec::codec::read_uvarint(bytes, &mut position)
            .expect("accept vector decodes"),
        16384_u64
    );
    assert_eq!(position, bytes.len());
    let mut encoded = Vec::new();
    rad::engine::exec::codec::append_uvarint(&mut encoded, 16384_u64);
    assert_eq!(encoded, bytes);
    // ten bytes, bit 63 set
    let bytes: &[u8] = &[0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01];
    let mut position = 0;
    assert_eq!(
        rad::engine::exec::codec::read_uvarint(bytes, &mut position)
            .expect("accept vector decodes"),
        18446744073709551615_u64
    );
    assert_eq!(position, bytes.len());
    let mut encoded = Vec::new();
    rad::engine::exec::codec::append_uvarint(&mut encoded, 18446744073709551615_u64);
    assert_eq!(encoded, bytes);
    // reject: truncated varint
    assert!(
        rad::engine::exec::codec::read_uvarint(&[], &mut 0).is_err(),
        "truncated varint"
    );
    // reject: truncated continuation
    assert!(
        rad::engine::exec::codec::read_uvarint(&[0x80], &mut 0).is_err(),
        "truncated continuation"
    );
    // reject: non-canonical: trailing zero group
    assert!(
        rad::engine::exec::codec::read_uvarint(&[0x80, 0x00], &mut 0).is_err(),
        "non-canonical: trailing zero group"
    );
    // reject: overflows 64 bits
    assert!(
        rad::engine::exec::codec::read_uvarint(
            &[0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x02],
            &mut 0
        )
        .is_err(),
        "overflows 64 bits"
    );
}

#[test]
fn uvarint_round_trip_for_seeded_samples() {
    let boundaries = [
        0_u64,
        1,
        127,
        128,
        255,
        16_383,
        16_384,
        u32::MAX as u64,
        u64::MAX >> 1,
        u64::MAX,
    ];
    let mut state = 0x6b65_7966_6f72_6d01_u64;
    let samples = boundaries
        .into_iter()
        .chain((0..4096).map(|_| splitmix64(&mut state)));
    for value in samples.collect::<Vec<_>>() {
        let mut encoded = Vec::new();
        rad::engine::exec::codec::append_uvarint(&mut encoded, value);
        let mut position = 0;
        assert_eq!(
            rad::engine::exec::codec::read_uvarint(&encoded, &mut position)
                .expect("encoded value decodes"),
            value
        );
        assert_eq!(position, encoded.len(), "self-delimiting for {value}");
    }
}

#[test]
fn ordered_scalar_tags_pin_the_cross_type_order() {
    assert_eq!(
        rad::engine::kv::key_encoding::TAG_NULL,
        0x01,
        "tag for null"
    );
    assert_eq!(
        rad::engine::kv::key_encoding::TAG_BOOL,
        0x02,
        "tag for bool"
    );
    assert_eq!(
        rad::engine::kv::key_encoding::TAG_I64,
        0x03,
        "tag for int64"
    );
    assert_eq!(
        rad::engine::kv::key_encoding::TAG_F64,
        0x04,
        "tag for float64"
    );
    assert_eq!(
        rad::engine::kv::key_encoding::TAG_TEXT,
        0x05,
        "tag for text"
    );
}

#[test]
fn ordered_scalar_vectors() {
    assert_eq!(
        kv_encode(&Value::Null(ScalarType::Text)).expect("vector value encodes"),
        &[0x01]
    );
    assert_eq!(
        kv_encode(&Value::Bool(false)).expect("vector value encodes"),
        &[0x02, 0x00]
    );
    assert_eq!(
        kv_encode(&Value::Bool(true)).expect("vector value encodes"),
        &[0x02, 0x01]
    );
    assert_eq!(
        kv_encode(&Value::Int64(0_i64)).expect("vector value encodes"),
        &[0x03, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    );
    // the key layer distinguishes the zero signs; the semantic layer above erases them
    assert_eq!(
        kv_encode(&Value::Float64(-0.0_f64)).expect("vector value encodes"),
        &[0x04, 0x7f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff]
    );
    assert_eq!(
        kv_encode(&Value::Text("".into())).expect("vector value encodes"),
        &[0x05, 0x00, 0x01]
    );
    assert_eq!(
        kv_encode(&Value::Text("a\0b".into())).expect("vector value encodes"),
        &[0x05, 0x61, 0x00, 0xff, 0x62, 0x00, 0x01]
    );
    let ordered_0 = kv_encode(&Value::Null(ScalarType::Text)).expect("order vector encodes");
    let ordered_1 = kv_encode(&Value::Bool(false)).expect("order vector encodes");
    let ordered_2 = kv_encode(&Value::Bool(true)).expect("order vector encodes");
    assert!(ordered_0 < ordered_1, "order vector must ascend");
    assert!(ordered_1 < ordered_2, "order vector must ascend");
    let ordered_3 = kv_encode(&Value::Int64(-1_i64)).expect("order vector encodes");
    let ordered_4 = kv_encode(&Value::Int64(0_i64)).expect("order vector encodes");
    let ordered_5 = kv_encode(&Value::Int64(1_i64)).expect("order vector encodes");
    assert!(ordered_3 < ordered_4, "order vector must ascend");
    assert!(ordered_4 < ordered_5, "order vector must ascend");
    let ordered_6 = kv_encode(&Value::Float64(-0.0_f64)).expect("order vector encodes");
    let ordered_7 = kv_encode(&Value::Float64(0.0_f64)).expect("order vector encodes");
    assert!(ordered_6 < ordered_7, "order vector must ascend");
    let ordered_8 =
        kv_encode(&Value::Float64(-1.7976931348623157e308_f64)).expect("order vector encodes");
    let ordered_9 = kv_encode(&Value::Float64(-1.5_f64)).expect("order vector encodes");
    let ordered_10 = kv_encode(&Value::Float64(1.5_f64)).expect("order vector encodes");
    let ordered_11 =
        kv_encode(&Value::Float64(1.7976931348623157e308_f64)).expect("order vector encodes");
    assert!(ordered_8 < ordered_9, "order vector must ascend");
    assert!(ordered_9 < ordered_10, "order vector must ascend");
    assert!(ordered_10 < ordered_11, "order vector must ascend");
    let ordered_12 = kv_encode(&Value::Text("".into())).expect("order vector encodes");
    let ordered_13 = kv_encode(&Value::Text("a".into())).expect("order vector encodes");
    let ordered_14 = kv_encode(&Value::Text("a\0".into())).expect("order vector encodes");
    let ordered_15 = kv_encode(&Value::Text("a\0b".into())).expect("order vector encodes");
    let ordered_16 = kv_encode(&Value::Text("app".into())).expect("order vector encodes");
    let ordered_17 = kv_encode(&Value::Text("apple".into())).expect("order vector encodes");
    let ordered_18 = kv_encode(&Value::Text("b".into())).expect("order vector encodes");
    assert!(ordered_12 < ordered_13, "order vector must ascend");
    assert!(ordered_13 < ordered_14, "order vector must ascend");
    assert!(ordered_14 < ordered_15, "order vector must ascend");
    assert!(ordered_15 < ordered_16, "order vector must ascend");
    assert!(ordered_16 < ordered_17, "order vector must ascend");
    assert!(ordered_17 < ordered_18, "order vector must ascend");
    let ordered_19 = kv_encode(&Value::Null(ScalarType::Text)).expect("order vector encodes");
    let ordered_20 = kv_encode(&Value::Bool(false)).expect("order vector encodes");
    let ordered_21 =
        kv_encode(&Value::Int64(9223372036854775807_i64)).expect("order vector encodes");
    let ordered_22 =
        kv_encode(&Value::Float64(-1.7976931348623157e308_f64)).expect("order vector encodes");
    let ordered_23 = kv_encode(&Value::Text("".into())).expect("order vector encodes");
    assert!(ordered_19 < ordered_20, "order vector must ascend");
    assert!(ordered_20 < ordered_21, "order vector must ascend");
    assert!(ordered_21 < ordered_22, "order vector must ascend");
    assert!(ordered_22 < ordered_23, "order vector must ascend");
}

#[test]
fn ordered_scalar_order_preserving_for_seeded_samples() {
    let mut state = 0x6b65_7966_6f72_6d07_u64;
    for _ in 0..4096 {
        let (left, right) = (splitmix64(&mut state) as i64, splitmix64(&mut state) as i64);
        assert_eq!(
            kv_encode(&Value::Int64(left))
                .expect("int64 encodes")
                .cmp(&kv_encode(&Value::Int64(right)).expect("int64 encodes")),
            left.cmp(&right),
            "int64 ordering mismatch for {left} and {right}"
        );
        let (left, right) = (
            f64::from_bits(splitmix64(&mut state)),
            f64::from_bits(splitmix64(&mut state)),
        );
        if !left.is_nan() && !right.is_nan() {
            assert_eq!(
                kv_encode(&Value::Float64(left))
                    .expect("non-NaN float64 encodes")
                    .cmp(&kv_encode(&Value::Float64(right)).expect("non-NaN float64 encodes")),
                left.total_cmp(&right),
                "float64 ordering mismatch for {left:?} and {right:?}"
            );
        }
    }
}

#[test]
fn semantic_scalar_vectors() {
    let bytes: &[u8] = &[0x01];
    let expected = Value::Null(ScalarType::Text);
    let (decoded, consumed) =
        rad::engine::exec::codec::decode_value(bytes).expect("accept vector decodes");
    assert_eq!(consumed, bytes.len());
    assert!(decoded.is_null());
    assert_eq!(
        rad::engine::exec::codec::encode_value(&expected).expect("accept vector encodes"),
        bytes
    );
    let bytes: &[u8] = &[0x02, 0x00];
    let expected = Value::Bool(false);
    let (decoded, consumed) =
        rad::engine::exec::codec::decode_value(bytes).expect("accept vector decodes");
    assert_eq!(consumed, bytes.len());
    assert_eq!(decoded, expected);
    assert_eq!(
        rad::engine::exec::codec::encode_value(&expected).expect("accept vector encodes"),
        bytes
    );
    let bytes: &[u8] = &[0x02, 0x01];
    let expected = Value::Bool(true);
    let (decoded, consumed) =
        rad::engine::exec::codec::decode_value(bytes).expect("accept vector decodes");
    assert_eq!(consumed, bytes.len());
    assert_eq!(decoded, expected);
    assert_eq!(
        rad::engine::exec::codec::encode_value(&expected).expect("accept vector encodes"),
        bytes
    );
    let bytes: &[u8] = &[0x03, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00];
    let expected = Value::Int64(0_i64);
    let (decoded, consumed) =
        rad::engine::exec::codec::decode_value(bytes).expect("accept vector decodes");
    assert_eq!(consumed, bytes.len());
    assert_eq!(decoded, expected);
    assert_eq!(
        rad::engine::exec::codec::encode_value(&expected).expect("accept vector encodes"),
        bytes
    );
    let bytes: &[u8] = &[0x03, 0x7f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff];
    let expected = Value::Int64(-1_i64);
    let (decoded, consumed) =
        rad::engine::exec::codec::decode_value(bytes).expect("accept vector decodes");
    assert_eq!(consumed, bytes.len());
    assert_eq!(decoded, expected);
    assert_eq!(
        rad::engine::exec::codec::encode_value(&expected).expect("accept vector encodes"),
        bytes
    );
    let bytes: &[u8] = &[0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00];
    let expected = Value::Int64(i64::MIN);
    let (decoded, consumed) =
        rad::engine::exec::codec::decode_value(bytes).expect("accept vector decodes");
    assert_eq!(consumed, bytes.len());
    assert_eq!(decoded, expected);
    assert_eq!(
        rad::engine::exec::codec::encode_value(&expected).expect("accept vector encodes"),
        bytes
    );
    let bytes: &[u8] = &[0x03, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff];
    let expected = Value::Int64(9223372036854775807_i64);
    let (decoded, consumed) =
        rad::engine::exec::codec::decode_value(bytes).expect("accept vector decodes");
    assert_eq!(consumed, bytes.len());
    assert_eq!(decoded, expected);
    assert_eq!(
        rad::engine::exec::codec::encode_value(&expected).expect("accept vector encodes"),
        bytes
    );
    let bytes: &[u8] = &[0x04, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00];
    let expected = Value::Float64(0.0_f64);
    let (decoded, consumed) =
        rad::engine::exec::codec::decode_value(bytes).expect("accept vector decodes");
    assert_eq!(consumed, bytes.len());
    assert_eq!(decoded, expected);
    assert_eq!(
        rad::engine::exec::codec::encode_value(&expected).expect("accept vector encodes"),
        bytes
    );
    let bytes: &[u8] = &[0x04, 0xbf, 0xf8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00];
    let expected = Value::Float64(1.5_f64);
    let (decoded, consumed) =
        rad::engine::exec::codec::decode_value(bytes).expect("accept vector decodes");
    assert_eq!(consumed, bytes.len());
    assert_eq!(decoded, expected);
    assert_eq!(
        rad::engine::exec::codec::encode_value(&expected).expect("accept vector encodes"),
        bytes
    );
    let bytes: &[u8] = &[0x04, 0x3f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff];
    let expected = Value::Float64(-2.0_f64);
    let (decoded, consumed) =
        rad::engine::exec::codec::decode_value(bytes).expect("accept vector decodes");
    assert_eq!(consumed, bytes.len());
    assert_eq!(decoded, expected);
    assert_eq!(
        rad::engine::exec::codec::encode_value(&expected).expect("accept vector encodes"),
        bytes
    );
    let bytes: &[u8] = &[0x05, 0x00, 0x01];
    let expected = Value::Text("".into());
    let (decoded, consumed) =
        rad::engine::exec::codec::decode_value(bytes).expect("accept vector decodes");
    assert_eq!(consumed, bytes.len());
    assert_eq!(decoded, expected);
    assert_eq!(
        rad::engine::exec::codec::encode_value(&expected).expect("accept vector encodes"),
        bytes
    );
    let bytes: &[u8] = &[0x05, 0x61, 0x00, 0x01];
    let expected = Value::Text("a".into());
    let (decoded, consumed) =
        rad::engine::exec::codec::decode_value(bytes).expect("accept vector decodes");
    assert_eq!(consumed, bytes.len());
    assert_eq!(decoded, expected);
    assert_eq!(
        rad::engine::exec::codec::encode_value(&expected).expect("accept vector encodes"),
        bytes
    );
    let bytes: &[u8] = &[0x05, 0x61, 0x00, 0xff, 0x62, 0x00, 0x01];
    let expected = Value::Text("a\0b".into());
    let (decoded, consumed) =
        rad::engine::exec::codec::decode_value(bytes).expect("accept vector decodes");
    assert_eq!(consumed, bytes.len());
    assert_eq!(decoded, expected);
    assert_eq!(
        rad::engine::exec::codec::encode_value(&expected).expect("accept vector encodes"),
        bytes
    );
    // reject: truncated encoded value
    assert!(
        rad::engine::exec::codec::decode_value(&[]).is_err(),
        "truncated encoded value"
    );
    // reject: unknown tag
    assert!(
        rad::engine::exec::codec::decode_value(&[0xff]).is_err(),
        "unknown tag"
    );
    // reject: truncated bool
    assert!(
        rad::engine::exec::codec::decode_value(&[0x02]).is_err(),
        "truncated bool"
    );
    // reject: malformed bool
    assert!(
        rad::engine::exec::codec::decode_value(&[0x02, 0x02]).is_err(),
        "malformed bool"
    );
    // reject: truncated int64
    assert!(
        rad::engine::exec::codec::decode_value(&[0x03, 0x00]).is_err(),
        "truncated int64"
    );
    // reject: -0.0 is not a canonical key
    assert!(
        rad::engine::exec::codec::decode_value(&[
            0x04, 0x7f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff
        ])
        .is_err(),
        "-0.0 is not a canonical key"
    );
    // reject: NaN never decodes
    assert!(
        rad::engine::exec::codec::decode_value(&[
            0x04, 0xff, 0xf8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
        ])
        .is_err(),
        "NaN never decodes"
    );
    // reject: infinity never decodes
    assert!(
        rad::engine::exec::codec::decode_value(&[
            0x04, 0xff, 0xf0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
        ])
        .is_err(),
        "infinity never decodes"
    );
    // reject: unterminated text
    assert!(
        rad::engine::exec::codec::decode_value(&[0x05, 0x61]).is_err(),
        "unterminated text"
    );
    // reject: truncated text escape
    assert!(
        rad::engine::exec::codec::decode_value(&[0x05, 0x61, 0x00]).is_err(),
        "truncated text escape"
    );
    // reject: malformed text escape
    assert!(
        rad::engine::exec::codec::decode_value(&[0x05, 0x61, 0x00, 0x02]).is_err(),
        "malformed text escape"
    );
}

#[test]
fn semantic_scalar_round_trip_and_canonical_bytes_for_seeded_samples() {
    let mut state = 0x6b65_7966_6f72_6d02_u64;
    for _ in 0..4096 {
        let value = generated_scalar(&mut state);
        let Ok(bytes) = rad::engine::exec::codec::encode_value(&value) else {
            continue;
        };
        let (decoded, consumed) =
            rad::engine::exec::codec::decode_value(&bytes).expect("encoded value decodes");
        assert_eq!(consumed, bytes.len());
        assert!(values_match(&decoded, &value), "round trip for {value:?}");
        assert_eq!(
            rad::engine::exec::codec::encode_value(&decoded).expect("decoded value re-encodes"),
            bytes,
            "canonical bytes for {value:?}"
        );
    }
}

#[test]
fn semantic_scalar_is_self_delimiting() {
    let mut state = 0x6b65_7966_6f72_6d03_u64;
    for _ in 0..2048 {
        let value = generated_scalar(&mut state);
        let Ok(bytes) = rad::engine::exec::codec::encode_value(&value) else {
            continue;
        };
        let mut extended = bytes.clone();
        extended.extend_from_slice(&[0xff, 0x00, 0x52, 0x01]);
        let (decoded, consumed) =
            rad::engine::exec::codec::decode_value(&extended).expect("prefix still decodes");
        assert_eq!(consumed, bytes.len());
        assert!(values_match(&decoded, &value));
    }
}

#[test]
fn semantic_scalar_order_matches_semantic_comparison() {
    let mut state = 0x6b65_7966_6f72_6d04_u64;
    for _ in 0..4096 {
        let left = generated_scalar(&mut state);
        let right = generated_scalar(&mut state);
        let Ok(expected) = left.compare(&right) else {
            continue;
        };
        let (Ok(left_bytes), Ok(right_bytes)) = (
            rad::engine::exec::codec::encode_value(&left),
            rad::engine::exec::codec::encode_value(&right),
        ) else {
            continue;
        };
        assert_eq!(
            left_bytes.cmp(&right_bytes),
            expected,
            "key order disagrees for {left:?} and {right:?}"
        );
    }
}

#[test]
fn key_tuple_round_trip_and_canonical_bytes_for_seeded_samples() {
    let mut state = 0x6b65_7966_6f72_6d05_u64;
    for _ in 0..1024 {
        let length = (splitmix64(&mut state) % 5) as usize;
        let values: Vec<Value> = (0..length).map(|_| generated_scalar(&mut state)).collect();
        let Ok(bytes) = rad::engine::exec::codec::encode_tuple(&values) else {
            continue;
        };
        let decoded =
            rad::engine::exec::codec::decode_tuple(&bytes).expect("encoded tuple decodes");
        assert_eq!(decoded.len(), values.len());
        for (actual, expected) in decoded.iter().zip(&values) {
            assert!(values_match(actual, expected));
        }
        assert_eq!(
            rad::engine::exec::codec::encode_tuple(&decoded).expect("decoded tuple re-encodes"),
            bytes
        );
    }
}

#[test]
fn key_tuple_concatenation_is_self_delimiting() {
    let mut state = 0x6b65_7966_6f72_6d06_u64;
    for _ in 0..1024 {
        let length = 1 + (splitmix64(&mut state) % 4) as usize;
        let values: Vec<Value> = (0..length).map(|_| generated_scalar(&mut state)).collect();
        let Ok(bytes) = rad::engine::exec::codec::encode_tuple(&values) else {
            continue;
        };
        let (first, consumed) =
            rad::engine::exec::codec::decode_value(&bytes).expect("first element decodes");
        assert!(values_match(&first, &values[0]));
        let rest = rad::engine::exec::codec::decode_tuple(&bytes[consumed..])
            .expect("remaining elements decode");
        assert_eq!(rest.len(), values.len() - 1);
        for (actual, expected) in rest.iter().zip(&values[1..]) {
            assert!(values_match(actual, expected));
        }
    }
}

#[test]
fn row_body_vectors() {
    let table = fuzz_rows_table();
    // canonical layout: every column stored
    let bytes: &[u8] = &[
        0x52, 0x04, 0x02, 0x01, 0x61, 0x02, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07,
        0x02, 0x01, 0x01, 0x02, 0x08, 0x3f, 0xf8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    ];
    let expected = Row::from([
        ("id".into(), Value::Text("a".into())),
        ("count".into(), Value::Int64(7_i64)),
        ("ready".into(), Value::Bool(true)),
        ("score".into(), Value::Float64(1.5_f64)),
    ]);
    assert_eq!(
        rad::engine::exec::codec::unmarshal_row(&table, bytes).expect("accept vector decodes"),
        expected
    );
    // explicit null count, absent ready and score: all three decode as typed nulls here because the fixture has no missing-value defaults
    let bytes: &[u8] = &[0x52, 0x02, 0x02, 0x01, 0x61, 0x03];
    let expected = Row::from([
        ("id".into(), Value::Text("a".into())),
        ("count".into(), Value::Null(ScalarType::Int64)),
        ("ready".into(), Value::Null(ScalarType::Bool)),
        ("score".into(), Value::Null(ScalarType::Float64)),
    ]);
    assert_eq!(
        rad::engine::exec::codec::unmarshal_row(&table, bytes).expect("accept vector decodes"),
        expected
    );
    // the empty body decodes to all nulls
    let bytes: &[u8] = &[0x52, 0x00];
    let expected = Row::from([
        ("id".into(), Value::Null(ScalarType::Text)),
        ("count".into(), Value::Null(ScalarType::Int64)),
        ("ready".into(), Value::Null(ScalarType::Bool)),
        ("score".into(), Value::Null(ScalarType::Float64)),
    ]);
    assert_eq!(
        rad::engine::exec::codec::unmarshal_row(&table, bytes).expect("accept vector decodes"),
        expected
    );
    // reject: missing canary
    assert!(
        rad::engine::exec::codec::unmarshal_row(&table, &[]).is_err(),
        "missing canary"
    );
    // reject: wrong canary
    assert!(
        rad::engine::exec::codec::unmarshal_row(&table, &[0x58, 0x00]).is_err(),
        "wrong canary"
    );
    // reject: truncated field count
    assert!(
        rad::engine::exec::codec::unmarshal_row(&table, &[0x52]).is_err(),
        "truncated field count"
    );
    // reject: field count exceeds remaining bytes
    assert!(
        rad::engine::exec::codec::unmarshal_row(
            &table,
            &[
                0x52, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01
            ]
        )
        .is_err(),
        "field count exceeds remaining bytes"
    );
    // reject: non-canonical header varint
    assert!(
        rad::engine::exec::codec::unmarshal_row(&table, &[0x52, 0x01, 0x80, 0x00]).is_err(),
        "non-canonical header varint"
    );
    // reject: zero delta: duplicate or non-ascending column ID
    assert!(
        rad::engine::exec::codec::unmarshal_row(&table, &[0x52, 0x01, 0x00]).is_err(),
        "zero delta: duplicate or non-ascending column ID"
    );
    // reject: payload truncated
    assert!(
        rad::engine::exec::codec::unmarshal_row(&table, &[0x52, 0x01, 0x02, 0x04, 0x61]).is_err(),
        "payload truncated"
    );
    // reject: trailing bytes
    assert!(
        rad::engine::exec::codec::unmarshal_row(&table, &[0x52, 0x00, 0xff]).is_err(),
        "trailing bytes"
    );
    // reject: invalid UTF-8 text payload
    assert!(
        rad::engine::exec::codec::unmarshal_row(&table, &[0x52, 0x01, 0x02, 0x01, 0xff]).is_err(),
        "invalid UTF-8 text payload"
    );
    // reject: int64 payload must be 8 bytes
    assert!(
        rad::engine::exec::codec::unmarshal_row(&table, &[0x52, 0x01, 0x04, 0x01, 0x07]).is_err(),
        "int64 payload must be 8 bytes"
    );
    // reject: malformed bool payload
    assert!(
        rad::engine::exec::codec::unmarshal_row(&table, &[0x52, 0x01, 0x06, 0x01, 0x02]).is_err(),
        "malformed bool payload"
    );
    // reject: non-finite float64 payload
    assert!(
        rad::engine::exec::codec::unmarshal_row(
            &table,
            &[
                0x52, 0x01, 0x08, 0x08, 0x7f, 0xf0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            ]
        )
        .is_err(),
        "non-finite float64 payload"
    );
    // reject: column ID beyond i64::MAX
    assert!(
        rad::engine::exec::codec::unmarshal_row(
            &table,
            &[
                0x52, 0x02, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0xff, 0xff,
                0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01
            ]
        )
        .is_err(),
        "column ID beyond i64::MAX"
    );
    // reject: fuzz find: an ID past the cap loses its top header bit when re-encoded
    assert!(
        rad::engine::exec::codec::unmarshal_row(
            &table,
            &[
                0x52, 0x04, 0x02, 0x02, 0x52, 0x04, 0x02, 0x08, 0x32, 0xf8, 0xfd, 0x04, 0x08, 0x04,
                0x52, 0x04, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0xff, 0xff,
                0xff, 0x47
            ]
        )
        .is_err(),
        "fuzz find: an ID past the cap loses its top header bit when re-encoded"
    );
    // reject: fuzz find: same family, maximal single delta
    assert!(
        rad::engine::exec::codec::unmarshal_row(
            &table,
            &[
                0x52, 0x03, 0x02, 0x01, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01,
                0x55
            ]
        )
        .is_err(),
        "fuzz find: same family, maximal single delta"
    );
}

#[test]
fn row_body_round_trip_and_canonical_bytes_for_seeded_samples() {
    let table = fuzz_rows_table();
    let mut state = 0x6b65_7966_6f72_6d08_u64;
    for _ in 0..1024 {
        let mut row = Row::new();
        for column in &table.columns {
            let value = match (splitmix64(&mut state) % 4, column.scalar_type) {
                (0, scalar_type) => Value::Null(scalar_type),
                (_, ScalarType::Text) => Value::Text(generated_text(&mut state)),
                (_, ScalarType::Int64) => Value::Int64(splitmix64(&mut state) as i64),
                (_, ScalarType::Bool) => Value::Bool(splitmix64(&mut state) % 2 == 1),
                (_, ScalarType::Float64) => {
                    let value = f64::from_bits(splitmix64(&mut state));
                    Value::Float64(if value.is_finite() { value } else { 0.5 })
                }
            };
            row.insert(column.name.clone(), value);
        }
        let bytes =
            rad::engine::exec::codec::marshal_row(&table, &row).expect("generated row encodes");
        let decoded =
            rad::engine::exec::codec::unmarshal_row(&table, &bytes).expect("encoded row decodes");
        assert_eq!(decoded.len(), row.len());
        for (column, expected) in &row {
            let actual = decoded
                .get(column)
                .expect("round trip preserves every column");
            assert!(
                values_match(actual, expected),
                "column {column} for {expected:?}"
            );
        }
        assert_eq!(
            rad::engine::exec::codec::marshal_row(&table, &decoded)
                .expect("decoded row re-encodes"),
            bytes
        );
    }
}

#[test]
fn row_body_cell_operations_form_an_algebra() {
    let table = fuzz_rows_table();
    let mut inputs: Vec<Vec<u8>> = vec![
        vec![
            0x52, 0x04, 0x02, 0x01, 0x61, 0x02, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x07, 0x02, 0x01, 0x01, 0x02, 0x08, 0x3f, 0xf8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        ],
        vec![0x52, 0x02, 0x02, 0x01, 0x61, 0x03],
        vec![0x52, 0x00],
        vec![],
        vec![0x58, 0x00],
        vec![0x52],
        vec![
            0x52, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01,
        ],
        vec![0x52, 0x01, 0x80, 0x00],
        vec![0x52, 0x01, 0x00],
        vec![0x52, 0x01, 0x02, 0x04, 0x61],
        vec![0x52, 0x00, 0xff],
        vec![0x52, 0x01, 0x02, 0x01, 0xff],
        vec![0x52, 0x01, 0x04, 0x01, 0x07],
        vec![0x52, 0x01, 0x06, 0x01, 0x02],
        vec![
            0x52, 0x01, 0x08, 0x08, 0x7f, 0xf0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        ],
        vec![
            0x52, 0x02, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0xff, 0xff,
            0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01,
        ],
        vec![
            0x52, 0x04, 0x02, 0x02, 0x52, 0x04, 0x02, 0x08, 0x32, 0xf8, 0xfd, 0x04, 0x08, 0x04,
            0x52, 0x04, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0xff, 0xff,
            0xff, 0x47,
        ],
        vec![
            0x52, 0x03, 0x02, 0x01, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01,
            0x55,
        ],
    ];
    let mut state = 0x6b65_7966_6f72_6d09_u64;
    for _ in 0..512 {
        let length = (splitmix64(&mut state) % 48) as usize;
        let mut bytes = vec![0x52];
        bytes.extend((0..length).map(|_| splitmix64(&mut state) as u8));
        inputs.push(bytes);
    }
    for input in &inputs {
        for column in &table.columns {
            let representative = match column.scalar_type {
                ScalarType::Text => Value::Text("fuzz\0text".into()),
                ScalarType::Int64 => Value::Int64(i64::MIN),
                ScalarType::Bool => Value::Bool(true),
                ScalarType::Float64 => Value::Float64(-0.0),
            };
            let _ = rad::engine::exec::codec::read_column_value(input, column);
            for value in [representative, Value::Null(column.scalar_type)] {
                let Ok(replaced) =
                    rad::engine::exec::codec::set_column_value(input, column, &value)
                else {
                    continue;
                };
                let actual = rad::engine::exec::codec::read_column_value(&replaced, column)
                    .expect("replacement is readable");
                assert_eq!(actual, value);
                if let (Value::Float64(actual), Value::Float64(expected)) = (&actual, &value) {
                    assert_eq!(actual.to_bits(), expected.to_bits());
                }
                assert_eq!(
                    rad::engine::exec::codec::set_column_value(&replaced, column, &value)
                        .expect("replacement is repeatable"),
                    replaced
                );
                let (removed, existed) =
                    rad::engine::exec::codec::remove_column(&replaced, &column.id)
                        .expect("replacement can be removed");
                assert!(existed);
                let (removed_again, existed_again) =
                    rad::engine::exec::codec::remove_column(&removed, &column.id)
                        .expect("removal is repeatable");
                assert!(!existed_again);
                assert_eq!(removed_again, removed);
            }
        }
    }
}

#[test]
fn keyspace_registry_is_coherent() {
    let spaces = rad::engine::kv::keyspace::KEYSPACES;
    assert_eq!(spaces.len(), 40);
    for space in spaces {
        assert!(!space.value.is_empty());
        assert!(
            !rad::engine::kv::keyspace::RESERVED_TAGS.contains(&space.tag),
            "space {} uses a reserved tag",
            space.name
        );
    }
    for left in spaces {
        for right in spaces {
            if std::ptr::eq(left, right) {
                continue;
            }
            assert_ne!(left.name, right.name, "duplicate space name");
            assert_ne!(
                left.tag, right.tag,
                "spaces {} and {} share a tag",
                left.name, right.name
            );
        }
    }
}

#[test]
fn data_key_vectors() {
    let key = rad::engine::kv::keys::data_key(42, 1, &[0x05, 0x61, 0x00, 0x01]);
    assert_eq!(key, &[0x72, 0x37, 0x01, 0x2a, 0x01, 0x05, 0x61, 0x00, 0x01]);
    let parts = rad::engine::kv::keys::decode_data_key(&key).expect("vector decodes");
    assert_eq!(parts.table, 42);
    assert_eq!(parts.generation, 1);
    assert_eq!(parts.primary_key, vec![0x05, 0x61, 0x00, 0x01]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
    // zero-length tuples are valid prefixes
    let key = rad::engine::kv::keys::data_key(1, 1, &[]);
    assert_eq!(key, &[0x72, 0x37, 0x01, 0x01, 0x01]);
    let parts = rad::engine::kv::keys::decode_data_key(&key).expect("vector decodes");
    assert_eq!(parts.table, 1);
    assert_eq!(parts.generation, 1);
    assert_eq!(parts.primary_key, Vec::<u8>::new());
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
    // maximum table number
    let key = rad::engine::kv::keys::data_key(18446744073709551615, 1, &[0x01]);
    assert_eq!(
        key,
        &[
            0x72, 0x37, 0x01, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x01,
            0x01
        ]
    );
    let parts = rad::engine::kv::keys::decode_data_key(&key).expect("vector decodes");
    assert_eq!(parts.table, 18446744073709551615);
    assert_eq!(parts.generation, 1);
    assert_eq!(parts.primary_key, vec![0x01]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn index_key_vectors() {
    let key = rad::engine::kv::keys::index_key(
        42,
        7,
        &[0x03, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
        &[0x05, 0x61, 0x00, 0x01],
    );
    assert_eq!(
        key,
        &[
            0x72, 0x37, 0x02, 0x2a, 0x07, 0x03, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x05, 0x61, 0x00, 0x01
        ]
    );
    let parts = rad::engine::kv::keys::decode_index_key(&key).expect("vector decodes");
    assert_eq!(parts.table, 42);
    assert_eq!(parts.index, 7);
    assert_eq!(
        parts.tuple_rest,
        vec![
            0x03, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05, 0x61, 0x00, 0x01
        ]
    );
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_table_object_key_vectors() {
    let key = rad::engine::kv::keys::catalog_table_object_key(7, 3);
    assert_eq!(
        key,
        &[
            0x72, 0x37, 0x10, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x03
        ]
    );
    let parts =
        rad::engine::kv::keys::decode_catalog_table_object_key(&key).expect("vector decodes");
    assert_eq!(parts.schema, 7);
    assert_eq!(parts.generation, 3);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_table_head_key_vectors() {
    let key = rad::engine::kv::keys::catalog_table_head_key(7);
    assert_eq!(key, &[0x72, 0x37, 0x11, 0x00, 0x00, 0x00, 0x07]);
    let parts = rad::engine::kv::keys::decode_catalog_table_head_key(&key).expect("vector decodes");
    assert_eq!(parts.schema, 7);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_table_key_vectors() {
    let key = rad::engine::kv::keys::catalog_table_key(42);
    assert_eq!(key, &[0x72, 0x37, 0x12, 0x2a]);
    let parts = rad::engine::kv::keys::decode_catalog_table_key(&key).expect("vector decodes");
    assert_eq!(parts.table, 42);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_table_name_key_vectors() {
    let key = rad::engine::kv::keys::catalog_table_name_key("users");
    assert_eq!(key, &[0x72, 0x37, 0x13, 0x75, 0x73, 0x65, 0x72, 0x73]);
    let parts = rad::engine::kv::keys::decode_catalog_table_name_key(&key).expect("vector decodes");
    assert_eq!(parts.name, "users");
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_schema_revision_key_vectors() {
    let key = rad::engine::kv::keys::catalog_schema_revision_key(12);
    assert_eq!(
        key,
        &[
            0x72, 0x37, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0c
        ]
    );
    let parts =
        rad::engine::kv::keys::decode_catalog_schema_revision_key(&key).expect("vector decodes");
    assert_eq!(parts.version, 12);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_write_protocol_object_key_vectors() {
    let key = rad::engine::kv::keys::catalog_write_protocol_object_key(42, 3);
    assert_eq!(
        key,
        &[
            0x72, 0x37, 0x15, 0x2a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03
        ]
    );
    let parts = rad::engine::kv::keys::decode_catalog_write_protocol_object_key(&key)
        .expect("vector decodes");
    assert_eq!(parts.table, 42);
    assert_eq!(parts.generation, 3);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_write_protocol_fence_key_vectors() {
    let key = rad::engine::kv::keys::catalog_write_protocol_fence_key(42);
    assert_eq!(key, &[0x72, 0x37, 0x16, 0x2a]);
    let parts = rad::engine::kv::keys::decode_catalog_write_protocol_fence_key(&key)
        .expect("vector decodes");
    assert_eq!(parts.table, 42);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_fence_table_existence_key_vectors() {
    let key = rad::engine::kv::keys::catalog_fence_table_existence_key(42);
    assert_eq!(key, &[0x72, 0x37, 0x17, 0x2a]);
    let parts = rad::engine::kv::keys::decode_catalog_fence_table_existence_key(&key)
        .expect("vector decodes");
    assert_eq!(parts.table, 42);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_fence_column_value_key_vectors() {
    let key = rad::engine::kv::keys::catalog_fence_column_value_key(42, 9);
    assert_eq!(key, &[0x72, 0x37, 0x18, 0x2a, 0x09]);
    let parts =
        rad::engine::kv::keys::decode_catalog_fence_column_value_key(&key).expect("vector decodes");
    assert_eq!(parts.table, 42);
    assert_eq!(parts.column, 9);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_fence_index_access_key_vectors() {
    let key = rad::engine::kv::keys::catalog_fence_index_access_key(42, 7);
    assert_eq!(key, &[0x72, 0x37, 0x19, 0x2a, 0x07]);
    let parts =
        rad::engine::kv::keys::decode_catalog_fence_index_access_key(&key).expect("vector decodes");
    assert_eq!(parts.table, 42);
    assert_eq!(parts.index, 7);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_transition_key_vectors() {
    let key = rad::engine::kv::keys::catalog_transition_key(5);
    assert_eq!(key, &[0x72, 0x37, 0x1a, 0x05]);
    let parts = rad::engine::kv::keys::decode_catalog_transition_key(&key).expect("vector decodes");
    assert_eq!(parts.transition, 5);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_transition_delta_key_vectors() {
    let key = rad::engine::kv::keys::catalog_transition_delta_key(5, 12);
    assert_eq!(
        key,
        &[
            0x72, 0x37, 0x1b, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0c
        ]
    );
    let parts =
        rad::engine::kv::keys::decode_catalog_transition_delta_key(&key).expect("vector decodes");
    assert_eq!(parts.transition, 5);
    assert_eq!(parts.sequence, 12);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_transition_delta_sequence_key_vectors() {
    let key = rad::engine::kv::keys::catalog_transition_delta_sequence_key(5);
    assert_eq!(key, &[0x72, 0x37, 0x1c, 0x05]);
    let parts = rad::engine::kv::keys::decode_catalog_transition_delta_sequence_key(&key)
        .expect("vector decodes");
    assert_eq!(parts.transition, 5);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_transition_delta_applied_key_vectors() {
    let key = rad::engine::kv::keys::catalog_transition_delta_applied_key(5);
    assert_eq!(key, &[0x72, 0x37, 0x1d, 0x05]);
    let parts = rad::engine::kv::keys::decode_catalog_transition_delta_applied_key(&key)
        .expect("vector decodes");
    assert_eq!(parts.transition, 5);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_transition_unique_claim_key_vectors() {
    let key = rad::engine::kv::keys::catalog_transition_unique_claim_key(
        5,
        &[0x03, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07],
        &[0x05, 0x61, 0x00, 0x01],
    );
    assert_eq!(
        key,
        &[
            0x72, 0x37, 0x1e, 0x05, 0x09, 0x03, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07,
            0x05, 0x61, 0x00, 0x01
        ]
    );
    let parts = rad::engine::kv::keys::decode_catalog_transition_unique_claim_key(&key)
        .expect("vector decodes");
    assert_eq!(parts.transition, 5);
    assert_eq!(
        parts.indexed,
        vec![0x03, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07]
    );
    assert_eq!(parts.primary_key, vec![0x05, 0x61, 0x00, 0x01]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_transition_unique_violation_key_vectors() {
    let key = rad::engine::kv::keys::catalog_transition_unique_violation_key(
        5,
        &[0x03, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07],
    );
    assert_eq!(
        key,
        &[
            0x72, 0x37, 0x1f, 0x05, 0x03, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07
        ]
    );
    let parts = rad::engine::kv::keys::decode_catalog_transition_unique_violation_key(&key)
        .expect("vector decodes");
    assert_eq!(parts.transition, 5);
    assert_eq!(
        parts.indexed,
        vec![0x03, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07]
    );
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_transition_violation_key_vectors() {
    let key = rad::engine::kv::keys::catalog_transition_violation_key(5, &[0xaa, 0xbb]);
    assert_eq!(key, &[0x72, 0x37, 0x20, 0x05, 0xaa, 0xbb]);
    let parts = rad::engine::kv::keys::decode_catalog_transition_violation_key(&key)
        .expect("vector decodes");
    assert_eq!(parts.transition, 5);
    assert_eq!(parts.row_identity, vec![0xaa, 0xbb]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_retention_pin_key_vectors() {
    let key = rad::engine::kv::keys::catalog_retention_pin_key("p1");
    assert_eq!(key, &[0x72, 0x37, 0x21, 0x70, 0x31]);
    let parts =
        rad::engine::kv::keys::decode_catalog_retention_pin_key(&key).expect("vector decodes");
    assert_eq!(parts.pin, "p1");
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_reclamation_key_vectors() {
    let key = rad::engine::kv::keys::catalog_reclamation_key("table-t1");
    assert_eq!(
        key,
        &[
            0x72, 0x37, 0x22, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2d, 0x74, 0x31
        ]
    );
    let parts =
        rad::engine::kv::keys::decode_catalog_reclamation_key(&key).expect("vector decodes");
    assert_eq!(parts.reclamation, "table-t1");
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_table_data_generation_stripe_key_vectors() {
    let key = rad::engine::kv::keys::catalog_table_data_generation_stripe_key(42, 7);
    assert_eq!(key, &[0x72, 0x37, 0x24, 0x2a, 0x07]);
    let parts = rad::engine::kv::keys::decode_catalog_table_data_generation_stripe_key(&key)
        .expect("vector decodes");
    assert_eq!(parts.table, 42);
    assert_eq!(parts.stripe, 7);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_meta_mode_key_vectors() {
    let key = rad::engine::kv::keys::catalog_meta_mode_key();
    assert_eq!(key, &[0x72, 0x37, 0x30]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_meta_next_id_key_vectors() {
    let key = rad::engine::kv::keys::catalog_meta_next_id_key();
    assert_eq!(key, &[0x72, 0x37, 0x31]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_meta_schema_version_key_vectors() {
    let key = rad::engine::kv::keys::catalog_meta_schema_version_key();
    assert_eq!(key, &[0x72, 0x37, 0x32]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_meta_catalog_generation_key_vectors() {
    let key = rad::engine::kv::keys::catalog_meta_catalog_generation_key();
    assert_eq!(key, &[0x72, 0x37, 0x33]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_meta_compacted_through_key_vectors() {
    let key = rad::engine::kv::keys::catalog_meta_compacted_through_key();
    assert_eq!(key, &[0x72, 0x37, 0x34]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_meta_transition_seen_key_vectors() {
    let key = rad::engine::kv::keys::catalog_meta_transition_seen_key();
    assert_eq!(key, &[0x72, 0x37, 0x35]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn catalog_meta_reclamation_seen_key_vectors() {
    let key = rad::engine::kv::keys::catalog_meta_reclamation_seen_key();
    assert_eq!(key, &[0x72, 0x37, 0x36]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn runtime_writer_fence_key_vectors() {
    let key = rad::engine::kv::keys::runtime_writer_fence_key();
    assert_eq!(key, &[0x72, 0x37, 0x40]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn storage_manifest_key_vectors() {
    let key = rad::engine::kv::keys::storage_manifest_key();
    assert_eq!(key, &[0x72, 0x37, 0x41]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn statistics_table_changes_key_vectors() {
    let key = rad::engine::kv::keys::statistics_table_changes_key(7);
    assert_eq!(key, &[0x72, 0x37, 0x50, 0x00, 0x00, 0x00, 0x07]);
    let parts =
        rad::engine::kv::keys::decode_statistics_table_changes_key(&key).expect("vector decodes");
    assert_eq!(parts.schema, 7);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn statistics_model_key_vectors() {
    let key = rad::engine::kv::keys::statistics_model_key(&[
        0x01, 0x01, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c,
        0x0d, 0x0e, 0x0f,
    ]);
    assert_eq!(
        key,
        &[
            0x72, 0x37, 0x51, 0x01, 0x01, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
            0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f
        ]
    );
    let parts = rad::engine::kv::keys::decode_statistics_model_key(&key).expect("vector decodes");
    assert_eq!(
        parts.family,
        vec![
            0x01, 0x01, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b,
            0x0c, 0x0d, 0x0e, 0x0f
        ]
    );
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn statistics_relation_model_key_vectors() {
    let key = rad::engine::kv::keys::statistics_relation_model_key(&[
        0x01, 0x01, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c,
        0x0d, 0x0e, 0x0f,
    ]);
    assert_eq!(
        key,
        &[
            0x72, 0x37, 0x55, 0x01, 0x01, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
            0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f
        ]
    );
    let parts =
        rad::engine::kv::keys::decode_statistics_relation_model_key(&key).expect("vector decodes");
    assert_eq!(
        parts.family,
        vec![
            0x01, 0x01, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b,
            0x0c, 0x0d, 0x0e, 0x0f
        ]
    );
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn statistics_model_catalog_key_vectors() {
    let key = rad::engine::kv::keys::statistics_model_catalog_key();
    assert_eq!(key, &[0x72, 0x37, 0x56]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn statistics_frequency_key_vectors() {
    let key = rad::engine::kv::keys::statistics_frequency_key(&[
        0x01, 0x01, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c,
        0x0d, 0x0e, 0x0f,
    ]);
    assert_eq!(
        key,
        &[
            0x72, 0x37, 0x57, 0x01, 0x01, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
            0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f
        ]
    );
    let parts =
        rad::engine::kv::keys::decode_statistics_frequency_key(&key).expect("vector decodes");
    assert_eq!(
        parts.family,
        vec![
            0x01, 0x01, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b,
            0x0c, 0x0d, 0x0e, 0x0f
        ]
    );
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn statistics_frequency_epoch_key_vectors() {
    let key = rad::engine::kv::keys::statistics_frequency_epoch_key();
    assert_eq!(key, &[0x72, 0x37, 0x58]);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn corpus_program_key_vectors() {
    let key = rad::engine::kv::keys::corpus_program_key(
        1,
        &[
            0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d,
            0x0e, 0x0f,
        ],
    );
    assert_eq!(
        key,
        &[
            0x72, 0x37, 0x52, 0x01, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09,
            0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f
        ]
    );
    let parts = rad::engine::kv::keys::decode_corpus_program_key(&key).expect("vector decodes");
    assert_eq!(parts.canonical_version, 1);
    assert_eq!(
        parts.content_hash,
        vec![
            0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d,
            0x0e, 0x0f
        ]
    );
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn corpus_execution_key_vectors() {
    let key = rad::engine::kv::keys::corpus_execution_key(1000000, 0);
    assert_eq!(
        key,
        &[
            0x72, 0x37, 0x53, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0f, 0x42, 0x40, 0x00
        ]
    );
    let parts = rad::engine::kv::keys::decode_corpus_execution_key(&key).expect("vector decodes");
    assert_eq!(parts.at, 1000000);
    assert_eq!(parts.sequence, 0);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn statistics_synopsis_key_vectors() {
    let key = rad::engine::kv::keys::statistics_synopsis_key(7);
    assert_eq!(key, &[0x72, 0x37, 0x54, 0x00, 0x00, 0x00, 0x07]);
    let parts =
        rad::engine::kv::keys::decode_statistics_synopsis_key(&key).expect("vector decodes");
    assert_eq!(parts.schema, 7);
    assert!(rad::engine::exec::key_describe::describe_key(&key).is_some());
}

#[test]
fn prefix_scan_bounds_are_smallest_and_exclusive() {
    assert_eq!(
        rad::engine::kv::key_encoding::prefix_end(&[0x01]),
        Some(vec![0x02])
    );
    assert_eq!(
        rad::engine::kv::key_encoding::prefix_end(&[0x61, 0x62, 0xff]),
        Some(vec![0x61, 0x63])
    );
    assert_eq!(
        rad::engine::kv::key_encoding::prefix_end(&[0xab, 0xcd]),
        Some(vec![0xab, 0xce])
    );
    assert_eq!(rad::engine::kv::key_encoding::prefix_end(&[0xff]), None);
    assert_eq!(rad::engine::kv::key_encoding::prefix_end(&[]), None);
    let mut state = 0x6b65_7966_6f72_6d0a_u64;
    for _ in 0..2048 {
        let length = 1 + (splitmix64(&mut state) % 6) as usize;
        let prefix: Vec<u8> = (0..length).map(|_| splitmix64(&mut state) as u8).collect();
        match rad::engine::kv::key_encoding::prefix_end(&prefix) {
            Some(end) => {
                assert!(prefix < end);
                assert!(end.len() <= prefix.len());
                for suffix in [&[][..], &[0x00][..], &[0xff][..], &[0xff, 0xff][..]] {
                    let mut key = prefix.clone();
                    key.extend_from_slice(suffix);
                    assert!(key < end, "suffixed key must stay under the bound");
                }
            }
            None => assert!(prefix.iter().all(|byte| *byte == 0xff)),
        }
    }
}
