// Code generated by opencli (rust-clap). DO NOT EDIT.
//
// Required dependency:
// clap = { version = "4.6", features = ["derive", "env"] }

use clap::{Args, Parser, Subcommand, ValueEnum};

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum GenerateLang {
    #[value(name = r"go")]
    Go,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum SchemaDiffFormat {
    #[value(name = r"text")]
    Text,
    #[value(name = r"json")]
    Json,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum ServeCatalogMode {
    #[value(name = r"direct")]
    Direct,
    #[value(name = r"schema")]
    Schema,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum ServeStorage {
    #[value(name = r"memory")]
    Memory,
    #[value(name = r"file")]
    File,
    #[value(name = r"s3")]
    S3,
}

#[derive(Debug, Parser)]
#[command(
    name = r"rad",
    version = r"0.1.0",
    about = r"The radically different database."
)]
pub struct Cli {
    #[command(flatten)]
    pub globals: GlobalArgs,

    #[command(subcommand)]
    pub command: RootCommand,
}

#[derive(Debug, Args)]
pub struct GlobalArgs {}

#[derive(Debug, Subcommand)]
pub enum RootCommand {
    #[command(
        name = r"init",
        about = r"Initialize a Rad project.",
        long_about = r"Create rad.config.yaml and rad.schema.yaml in a new or existing project directory. In a terminal, Rad guides you through the small set of project choices. Use --yes to accept defaults without prompts. Existing project files are never overwritten, and accepted rad.state is created only by a successful schema migration or pull.
"
    )]
    Init(InitArgs),
    #[command(name = r"serve", about = r"Run the Rad database server.")]
    Serve(ServeArgs),
    #[command(
        name = r"validate",
        about = r"Validate a rad.schema.yaml file.",
        long_about = r"Parse and validate the schema structure, types, and references locally without calling out to the remote database.
"
    )]
    Validate(ValidateArgs),
    #[command(name = r"schema", about = r"Inspect and manage the database schema.")]
    Schema(SchemaArgs),
    #[command(
        name = r"generate",
        about = r"Generate a typed client for the accepted schema.",
        long_about = r"Generate a typed client from the accepted schema state recorded by rad schema migrate or rad schema pull. The lockfile points to an immutable changelog snapshot so generation cannot silently target unapplied local schema changes. rad generate reads this state; it does not create it.
"
    )]
    Generate(GenerateArgs),
}

#[allow(async_fn_in_trait)]
pub trait Handler {
    type Error;

    async fn init(&mut self, globals: &GlobalArgs, args: InitArgs) -> Result<(), Self::Error>;
    async fn serve(&mut self, globals: &GlobalArgs, args: ServeArgs) -> Result<(), Self::Error>;
    async fn validate(
        &mut self,
        globals: &GlobalArgs,
        args: ValidateArgs,
    ) -> Result<(), Self::Error>;
    async fn schema_status(
        &mut self,
        globals: &GlobalArgs,
        context_schema: &SchemaOptions,
        args: SchemaStatusArgs,
    ) -> Result<(), Self::Error>;
    async fn schema_diff(
        &mut self,
        globals: &GlobalArgs,
        context_schema: &SchemaOptions,
        args: SchemaDiffArgs,
    ) -> Result<(), Self::Error>;
    async fn schema_migrate(
        &mut self,
        globals: &GlobalArgs,
        context_schema: &SchemaOptions,
        args: SchemaMigrateArgs,
    ) -> Result<(), Self::Error>;
    async fn schema_pull(
        &mut self,
        globals: &GlobalArgs,
        context_schema: &SchemaOptions,
        args: SchemaPullArgs,
    ) -> Result<(), Self::Error>;
    async fn generate(
        &mut self,
        globals: &GlobalArgs,
        args: GenerateArgs,
    ) -> Result<(), Self::Error>;
}

impl Cli {
    pub async fn dispatch<H: Handler>(self, handler: &mut H) -> Result<(), H::Error> {
        self.command.dispatch(&self.globals, handler).await
    }
}

impl RootCommand {
    async fn dispatch<H: Handler>(
        self,
        globals: &GlobalArgs,
        handler: &mut H,
    ) -> Result<(), H::Error> {
        match self {
            Self::Init(args) => args.dispatch(globals, handler).await,
            Self::Serve(args) => args.dispatch(globals, handler).await,
            Self::Validate(args) => args.dispatch(globals, handler).await,
            Self::Schema(args) => args.dispatch(globals, handler).await,
            Self::Generate(args) => args.dispatch(globals, handler).await,
        }
    }
}

#[derive(Debug, Args)]
pub struct InitArgs {
    #[arg(
        id = r"database-url",
        long = r"database-url",
        help = r"Rad database URL written to the project configuration.",
        default_value = r"rad://127.0.0.1:7237"
    )]
    pub database_url: String,
    #[arg(
        id = r"out",
        long = r"out",
        short = 'o',
        help = r"Generated Go client output directory.",
        default_value = r"generated"
    )]
    pub out: std::path::PathBuf,
    #[arg(
        id = r"pkg",
        long = r"pkg",
        help = r"Generated Go package name.",
        default_value = r"db"
    )]
    pub pkg: String,
    #[arg(
        id = r"no-generate",
        long = r"no-generate",
        help = r"Do not configure generated client output."
    )]
    pub no_generate: bool,
    #[arg(
        id = r"empty",
        long = r"empty",
        help = r"Create an empty schema instead of the starter users table."
    )]
    pub empty: bool,
    #[arg(
        id = r"yes",
        long = r"yes",
        short = 'y',
        help = r"Accept supplied values and defaults without prompting."
    )]
    pub yes: bool,
    #[arg(
        id = r"DIRECTORY",
        index = 1,
        help = r"Directory to initialize.",
        default_value = r"."
    )]
    pub directory: std::path::PathBuf,
}

impl InitArgs {
    pub const OPERATION_ID: &'static str = r"init";
}

impl InitArgs {
    async fn dispatch<H: Handler>(
        self,
        globals: &GlobalArgs,
        handler: &mut H,
    ) -> Result<(), H::Error> {
        handler.init(globals, self).await
    }
}
#[derive(Debug, Args)]
pub struct ServeArgs {
    #[arg(
        id = r"addr",
        long = r"addr",
        help = r"HTTP server listen address.",
        env = r"RAD_ADDR",
        default_value = r"0.0.0.0:7237"
    )]
    pub addr: String,
    #[arg(
        id = r"storage",
        long = r"storage",
        help = r"Storage backend.",
        env = r"RAD_STORAGE",
        default_value = r"file",
        value_enum
    )]
    pub storage: ServeStorage,
    #[arg(
        id = r"db",
        long = r"db",
        short = 'd',
        help = r"File storage directory.",
        env = r"RAD_DATA_DIR",
        default_value = r"data"
    )]
    pub db: std::path::PathBuf,
    #[arg(
        id = r"storage-path",
        long = r"storage-path",
        help = r"Logical SlateDB path within the selected backend.",
        env = r"RAD_STORAGE_PATH",
        default_value = r"rad"
    )]
    pub storage_path: String,
    #[arg(
        id = r"catalog-mode",
        long = r"catalog-mode",
        help = r"Catalog mode for a fresh database; immutable after initialization.",
        env = r"RAD_CATALOG_MODE",
        value_enum
    )]
    pub catalog_mode: Option<ServeCatalogMode>,
    #[arg(
        id = r"s3-bucket",
        long = r"s3-bucket",
        help = r"S3 bucket used by the s3 storage backend.",
        env = r"RAD_S3_BUCKET"
    )]
    pub s3_bucket: Option<String>,
    #[arg(
        id = r"s3-prefix",
        long = r"s3-prefix",
        help = r"S3 object prefix; defaults to --storage-path.",
        env = r"RAD_S3_PREFIX"
    )]
    pub s3_prefix: Option<String>,
    #[arg(
        id = r"s3-region",
        long = r"s3-region",
        help = r"S3 region.",
        env = r"RAD_S3_REGION"
    )]
    pub s3_region: Option<String>,
    #[arg(
        id = r"s3-endpoint",
        long = r"s3-endpoint",
        help = r"Custom S3-compatible endpoint, such as RustFS.",
        env = r"RAD_S3_ENDPOINT"
    )]
    pub s3_endpoint: Option<String>,
}

impl ServeArgs {
    pub const OPERATION_ID: &'static str = r"serve";
}

impl ServeArgs {
    async fn dispatch<H: Handler>(
        self,
        globals: &GlobalArgs,
        handler: &mut H,
    ) -> Result<(), H::Error> {
        handler.serve(globals, self).await
    }
}
#[derive(Debug, Args)]
pub struct ValidateArgs {
    #[arg(
        id = r"file",
        long = r"file",
        short = 'f',
        help = r"Desired schema file.",
        default_value = r"rad.schema.yaml"
    )]
    pub file: std::path::PathBuf,
}

impl ValidateArgs {
    pub const OPERATION_ID: &'static str = r"validate";
}

impl ValidateArgs {
    async fn dispatch<H: Handler>(
        self,
        globals: &GlobalArgs,
        handler: &mut H,
    ) -> Result<(), H::Error> {
        handler.validate(globals, self).await
    }
}
#[derive(Debug, Args)]
pub struct SchemaArgs {
    #[command(flatten)]
    pub options: SchemaOptions,

    #[command(subcommand)]
    pub command: SchemaCommand,
}

#[derive(Debug, Args)]
pub struct SchemaOptions {
    #[arg(
        id = r"config",
        long = r"config",
        help = r"Project configuration file.",
        default_value = r"rad.config.yaml"
    )]
    pub config: std::path::PathBuf,
    #[arg(
        id = r"file",
        long = r"file",
        short = 'f',
        help = r"Desired schema file.",
        default_value = r"rad.schema.yaml"
    )]
    pub file: std::path::PathBuf,
}

impl SchemaArgs {
    async fn dispatch<H: Handler>(
        self,
        globals: &GlobalArgs,
        handler: &mut H,
    ) -> Result<(), H::Error> {
        self.command.dispatch(globals, &self.options, handler).await
    }
}
#[derive(Debug, Subcommand)]
pub enum SchemaCommand {
    #[command(
        name = r"status",
        about = r"Compare server, accepted, desired, and generated schemas."
    )]
    Status(SchemaStatusArgs),
    #[command(
        name = r"diff",
        about = r"Show desired schema changes and data preflight findings."
    )]
    Diff(SchemaDiffArgs),
    #[command(name = r"migrate", about = r"Apply rad.schema.yaml transactionally.")]
    Migrate(SchemaMigrateArgs),
    #[command(
        name = r"pull",
        about = r"Recover the accepted schema from the database."
    )]
    Pull(SchemaPullArgs),
}

impl SchemaCommand {
    async fn dispatch<H: Handler>(
        self,
        globals: &GlobalArgs,
        context_schema: &SchemaOptions,
        handler: &mut H,
    ) -> Result<(), H::Error> {
        match self {
            Self::Status(args) => args.dispatch(globals, context_schema, handler).await,
            Self::Diff(args) => args.dispatch(globals, context_schema, handler).await,
            Self::Migrate(args) => args.dispatch(globals, context_schema, handler).await,
            Self::Pull(args) => args.dispatch(globals, context_schema, handler).await,
        }
    }
}

#[derive(Debug, Args)]
pub struct SchemaStatusArgs {}

impl SchemaStatusArgs {
    pub const OPERATION_ID: &'static str = r"schemaStatus";
}

impl SchemaStatusArgs {
    async fn dispatch<H: Handler>(
        self,
        globals: &GlobalArgs,
        context_schema: &SchemaOptions,
        handler: &mut H,
    ) -> Result<(), H::Error> {
        handler.schema_status(globals, context_schema, self).await
    }
}
#[derive(Debug, Args)]
pub struct SchemaDiffArgs {
    #[arg(
        id = r"format",
        long = r"format",
        help = r"Output format.",
        default_value = r"text",
        value_enum
    )]
    pub format: SchemaDiffFormat,
}

impl SchemaDiffArgs {
    pub const OPERATION_ID: &'static str = r"schemaDiff";
}

impl SchemaDiffArgs {
    async fn dispatch<H: Handler>(
        self,
        globals: &GlobalArgs,
        context_schema: &SchemaOptions,
        handler: &mut H,
    ) -> Result<(), H::Error> {
        handler.schema_diff(globals, context_schema, self).await
    }
}
#[derive(Debug, Args)]
pub struct SchemaMigrateArgs {
    #[arg(
        id = r"accept-data-loss",
        long = r"accept-data-loss",
        help = r"Permit explicitly reported destructive changes."
    )]
    pub accept_data_loss: bool,
    #[arg(
        id = r"no-generate",
        long = r"no-generate",
        help = r"Do not regenerate configured clients."
    )]
    pub no_generate: bool,
}

impl SchemaMigrateArgs {
    pub const OPERATION_ID: &'static str = r"schemaMigrate";
}

impl SchemaMigrateArgs {
    async fn dispatch<H: Handler>(
        self,
        globals: &GlobalArgs,
        context_schema: &SchemaOptions,
        handler: &mut H,
    ) -> Result<(), H::Error> {
        handler.schema_migrate(globals, context_schema, self).await
    }
}
#[derive(Debug, Args)]
pub struct SchemaPullArgs {
    #[arg(
        id = r"force",
        long = r"force",
        help = r"Back up and replace a locally modified schema."
    )]
    pub force: bool,
    #[arg(
        id = r"no-generate",
        long = r"no-generate",
        help = r"Do not regenerate configured clients."
    )]
    pub no_generate: bool,
}

impl SchemaPullArgs {
    pub const OPERATION_ID: &'static str = r"schemaPull";
}

impl SchemaPullArgs {
    async fn dispatch<H: Handler>(
        self,
        globals: &GlobalArgs,
        context_schema: &SchemaOptions,
        handler: &mut H,
    ) -> Result<(), H::Error> {
        handler.schema_pull(globals, context_schema, self).await
    }
}
#[derive(Debug, Args)]
pub struct GenerateArgs {
    #[arg(
        id = r"file",
        long = r"file",
        short = 'f',
        help = r"Desired schema file.",
        default_value = r"rad.schema.yaml"
    )]
    pub file: std::path::PathBuf,
    #[arg(
        id = r"out",
        long = r"out",
        short = 'o',
        help = r"Output directory.",
        default_value = r"generated"
    )]
    pub out: std::path::PathBuf,
    #[arg(
        id = r"pkg",
        long = r"pkg",
        help = r"Generated package or client name.",
        default_value = r"db"
    )]
    pub pkg: String,
    #[arg(
        id = r"lang",
        long = r"lang",
        help = r"Client language.",
        default_value = r"go",
        value_enum
    )]
    pub lang: GenerateLang,
}

impl GenerateArgs {
    pub const OPERATION_ID: &'static str = r"generate";
}

impl GenerateArgs {
    async fn dispatch<H: Handler>(
        self,
        globals: &GlobalArgs,
        handler: &mut H,
    ) -> Result<(), H::Error> {
        handler.generate(globals, self).await
    }
}
