package codegen

import (
	"bytes"
	"fmt"
	"go/format"

	"rad/rad/02_catalog/schema"
)

// Generate emits the typed Go client for a schema as a single gofmt-ed
// source file declaring package pkg. The generated code talks to a RAD
// server over the rad:// protocol via the radclient runtime — it has no
// engine imports and works from any process that can reach the server.
// schemaSrc is embedded verbatim so the client can migrate its database.
func Generate(pkg string, sch *schema.Schema, schemaSrc []byte) ([]byte, error) {
	m, err := build(pkg, sch)
	if err != nil {
		return nil, err
	}

	var b bytes.Buffer
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	emitHeader(p, m, schemaSrc)
	for _, t := range m.Tables {
		emitModel(p, t)
		emitCreateAndPatch(p, t)
		emitTableHandle(p, t)
		emitQuery(p, t)
		emitInclude(p, t)
		emitConverters(p, t)
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: generated source does not format (bug): %w\n%s", err, b.Bytes())
	}
	return src, nil
}

func emitHeader(p func(string, ...any), m *genModel, schemaSrc []byte) {
	p("// Code generated by rad generate. DO NOT EDIT.")
	p("//")
	p("// Typed client for a RAD database, speaking the rad:// wire protocol.")
	p("// No SQL anywhere — queries compile to RAD's QIR on the wire.")
	p("package %s", m.Pkg)
	p("")
	p("import (")
	p("\t\"context\"")
	p("\t\"encoding/json\"")
	p("")
	p("\tradclient \"rad/client\"")
	p("\t\"rad/protocol\"")
	p(")")
	p("")
	p("// SchemaSource is the schema.rad this client was generated from.")
	p("const SchemaSource = %q", string(schemaSrc))
	p("")

	p("// Client is the database handle: Connect to a RAD server, then use the")
	p("// table handles. All methods are safe for concurrent use.")
	p("type Client struct {")
	p("\trc *radclient.Client")
	for _, t := range m.Tables {
		p("\t%s %sTable", goName(t.SQLName), t.Model)
	}
	p("}")
	p("")
	p("// Connect dials a RAD server, e.g. Connect(\"rad://localhost\").")
	p("func Connect(url string, opts ...radclient.Option) (*Client, error) {")
	p("\trc, err := radclient.Dial(url, opts...)")
	p("\tif err != nil {")
	p("\t\treturn nil, err")
	p("\t}")
	p("\treturn New(rc), nil")
	p("}")
	p("")
	p("// New wraps an existing runtime client.")
	p("func New(rc *radclient.Client) *Client {")
	p("\tc := &Client{rc: rc}")
	for _, t := range m.Tables {
		p("\tc.%s = %sTable{v: rc}", goName(t.SQLName), t.Model)
	}
	p("\treturn c")
	p("}")
	p("")
	p("// Runtime exposes the underlying protocol client.")
	p("func (c *Client) Runtime() *radclient.Client { return c.rc }")
	p("")
	p("// Ping verifies the server is reachable.")
	p("func (c *Client) Ping(ctx context.Context) error { return c.rc.Ping(ctx) }")
	p("")
	p("// Migrate reconciles the server's database with SchemaSource and")
	p("// returns the applied steps.")
	p("func (c *Client) Migrate(ctx context.Context) ([]string, error) {")
	p("\treturn c.rc.Migrate(ctx, SchemaSource)")
	p("}")
	p("")
	p("// Tx runs fn in a server-held serializable transaction; retry the whole")
	p("// Tx when IsConflict(err).")
	p("func (c *Client) Tx(ctx context.Context, fn func(tx *Tx) error) error {")
	p("\treturn c.rc.Txn(ctx, func(rtx *radclient.Tx) error {")
	p("\t\ttx := &Tx{}")
	for _, t := range m.Tables {
		p("\t\ttx.%s = %sTable{v: rtx}", goName(t.SQLName), t.Model)
	}
	p("\t\treturn fn(tx)")
	p("\t})")
	p("}")
	p("")
	p("// IsConflict reports whether err is a transaction conflict worth retrying.")
	p("func IsConflict(err error) bool { return radclient.IsConflict(err) }")
	p("")
	p("// Tx mirrors the Client's table handles inside a transaction.")
	p("type Tx struct {")
	for _, t := range m.Tables {
		p("\t%s %sTable", goName(t.SQLName), t.Model)
	}
	p("}")
	p("")

	// Expression combinators + record decoding helpers (json.Number-aware).
	p("// andExpr folds filters into a single expression (nil when empty).")
	p("func andExpr(filters []protocol.Expr) *protocol.Expr {")
	p("\tswitch len(filters) {")
	p("\tcase 0:")
	p("\t\treturn nil")
	p("\tcase 1:")
	p("\t\treturn &filters[0]")
	p("\tdefault:")
	p("\t\treturn &protocol.Expr{Op: \"and\", Exprs: filters}")
	p("\t}")
	p("}")
	p("")
	for _, h := range []struct{ name, typ, cast string }{
		{"recString", "string", "s, _ := m[k].(string)\n\treturn s"},
		{"recBool", "bool", "b, _ := m[k].(bool)\n\treturn b"},
	} {
		p("func %s(m protocol.Record, k string) %s {", h.name, h.typ)
		p("\t" + h.cast)
		p("}")
		p("")
	}
	p("func recInt64(m protocol.Record, k string) int64 {")
	p("\tn, _ := m[k].(json.Number)")
	p("\ti, _ := n.Int64()")
	p("\treturn i")
	p("}")
	p("")
	p("func recFloat64(m protocol.Record, k string) float64 {")
	p("\tn, _ := m[k].(json.Number)")
	p("\tf, _ := n.Float64()")
	p("\treturn f")
	p("}")
	p("")
	for _, h := range []struct{ name, typ, base string }{
		{"recStringPtr", "string", "recString"},
		{"recInt64Ptr", "int64", "recInt64"},
		{"recFloat64Ptr", "float64", "recFloat64"},
		{"recBoolPtr", "bool", "recBool"},
	} {
		p("func %s(m protocol.Record, k string) *%s {", h.name, h.typ)
		p("\tif m[k] == nil {")
		p("\t\treturn nil")
		p("\t}")
		p("\tv := %s(m, k)", h.base)
		p("\treturn &v")
		p("}")
		p("")
	}
}

// emitModel writes the row struct: columns, then forward relation pointers,
// then reverse relation slices (populated only when included).
func emitModel(p func(string, ...any), t *genTable) {
	p("// %s is one row of %q. Relation fields are populated only when the", t.Model, t.SQLName)
	p("// corresponding Include* option was used on the query.")
	p("type %s struct {", t.Model)
	for _, c := range t.Cols {
		typ := c.GoType
		if c.Nullable {
			typ = "*" + c.GoType
		}
		p("\t%s %s `json:%q`", c.Field, typ, c.SQLName+jsonOmit(c.Nullable))
	}
	for _, r := range t.Forward {
		p("\t%s *%s `json:%q`", r.Field, r.Target.Model, r.As+",omitempty")
	}
	for _, r := range t.Reverse {
		p("\t%s []%s `json:%q`", r.Field, r.Target.Model, r.As+",omitempty")
	}
	p("}")
	p("")
}

func jsonOmit(nullable bool) string {
	if nullable {
		return ",omitempty"
	}
	return ""
}

// emitCreateAndPatch writes the input structs: required fields are bare,
// optional (nullable or defaulted) fields are pointers.
func emitCreateAndPatch(p func(string, ...any), t *genTable) {
	p("// %sCreate is the input to Create. Pointer fields are optional:", t.Model)
	p("// nil defers to the column default or NULL.")
	p("type %sCreate struct {", t.Model)
	for _, c := range t.Cols {
		if c.Nullable || c.HasDef {
			p("\t%s *%s", c.Field, c.GoType)
		} else {
			p("\t%s %s", c.Field, c.GoType)
		}
	}
	p("}")
	p("")
	p("// %sPatch is the input to Update. Nil fields are left untouched;", t.Model)
	p("// Clear* sets a nullable column to NULL.")
	p("type %sPatch struct {", t.Model)
	for _, c := range t.Cols {
		if c.IsPK {
			continue
		}
		p("\t%s *%s", c.Field, c.GoType)
	}
	for _, c := range t.Cols {
		if c.IsPK || !c.Nullable {
			continue
		}
		p("\tClear%s bool", c.Field)
	}
	p("}")
	p("")
}

// pkParams renders the primary key as Go parameters, e.g.
// "teamID string, userID string".
func pkParams(t *genTable) string {
	out := ""
	for i, c := range t.PK {
		if i > 0 {
			out += ", "
		}
		out += lowerFirst(c.Field) + " " + c.GoType
	}
	return out
}

// pkKeyMap renders the wire key map from PK parameters.
func pkKeyMap(t *genTable) string {
	out := "map[string]any{"
	for i, c := range t.PK {
		if i > 0 {
			out += ", "
		}
		out += fmt.Sprintf("%q: %s", c.SQLName, lowerFirst(c.Field))
	}
	return out + "}"
}

func lowerFirst(s string) string {
	if s == "ID" {
		return "id"
	}
	out := []byte(s)
	out[0] = out[0] - 'A' + 'a'
	return string(out)
}

// emitTableHandle writes CRUD + unique lookups.
func emitTableHandle(p func(string, ...any), t *genTable) {
	h := t.Model + "Table"
	p("// %s provides typed access to %q.", h, t.SQLName)
	p("type %s struct{ v radclient.View }", h)
	p("")

	// Create.
	p("func (t %s) Create(ctx context.Context, in %sCreate) (%s, error) {", h, t.Model, t.Model)
	p("\tvalues := map[string]any{}")
	for _, c := range t.Cols {
		if c.Nullable || c.HasDef {
			p("\tif in.%s != nil {", c.Field)
			p("\t\tvalues[%q] = *in.%s", c.SQLName, c.Field)
			p("\t}")
		} else {
			p("\tvalues[%q] = in.%s", c.SQLName, c.Field)
		}
	}
	p("\trec, err := t.v.Create(ctx, %q, values)", t.SQLName)
	p("\tif err != nil {")
	p("\t\treturn %s{}, err", t.Model)
	p("\t}")
	p("\treturn %sFromRecord(rec), nil", lowerFirst(t.Model))
	p("}")
	p("")

	// Get by primary key.
	p("func (t %s) Get(ctx context.Context, %s) (%s, bool, error) {", h, pkParams(t), t.Model)
	p("\trec, found, err := t.v.Get(ctx, %q, %s)", t.SQLName, pkKeyMap(t))
	p("\tif err != nil || !found {")
	p("\t\treturn %s{}, false, err", t.Model)
	p("\t}")
	p("\treturn %sFromRecord(rec), true, nil", lowerFirst(t.Model))
	p("}")
	p("")

	// Update by primary key.
	p("func (t %s) Update(ctx context.Context, %s, patch %sPatch) (%s, bool, error) {", h, pkParams(t), t.Model, t.Model)
	p("\tset := map[string]any{}")
	p("\tvar clear []string")
	for _, c := range t.Cols {
		if c.IsPK {
			continue
		}
		p("\tif patch.%s != nil {", c.Field)
		p("\t\tset[%q] = *patch.%s", c.SQLName, c.Field)
		p("\t}")
		if c.Nullable {
			p("\tif patch.Clear%s {", c.Field)
			p("\t\tclear = append(clear, %q)", c.SQLName)
			p("\t}")
		}
	}
	p("\trec, found, err := t.v.Update(ctx, %q, %s, set, clear)", t.SQLName, pkKeyMap(t))
	p("\tif err != nil || !found {")
	p("\t\treturn %s{}, false, err", t.Model)
	p("\t}")
	p("\treturn %sFromRecord(rec), true, nil", lowerFirst(t.Model))
	p("}")
	p("")

	// Delete by primary key.
	p("func (t %s) Delete(ctx context.Context, %s) (bool, error) {", h, pkParams(t))
	p("\treturn t.v.Delete(ctx, %q, %s)", t.SQLName, pkKeyMap(t))
	p("}")
	p("")

	// Unique lookups.
	for _, uq := range t.Uniques {
		name := "By"
		params := ""
		for i, c := range uq {
			name += c.Field
			if i > 0 {
				params += ", "
			}
			params += lowerFirst(c.Field) + " " + c.GoType
		}
		p("// %s finds the row by the unique index on (%s).", name, uqCols(uq))
		p("func (t %s) %s(ctx context.Context, %s) (%s, bool, error) {", h, name, params, t.Model)
		p("\trecs, err := t.v.Query(ctx, protocol.Read{Table: %q, Filter: andExpr([]protocol.Expr{", t.SQLName)
		for _, c := range uq {
			p("\t\t{Op: \"eq\", Column: %q, Value: %s},", c.SQLName, lowerFirst(c.Field))
		}
		p("\t}), Limit: 1})")
		p("\tif err != nil || len(recs) == 0 {")
		p("\t\treturn %s{}, false, err", t.Model)
		p("\t}")
		p("\treturn %sFromRecord(recs[0]), true, nil", lowerFirst(t.Model))
		p("}")
		p("")
	}

	// Query entry point.
	p("func (t %s) Query() *%sQuery {", h, t.Model)
	p("\treturn &%sQuery{v: t.v, read: protocol.Read{Table: %q}}", t.Model, t.SQLName)
	p("}")
	p("")
}

func uqCols(uq []genCol) string {
	out := ""
	for i, c := range uq {
		if i > 0 {
			out += ", "
		}
		out += c.SQLName
	}
	return out
}

// emitQuery writes the fluent query builder.
func emitQuery(p func(string, ...any), t *genTable) {
	q := t.Model + "Query"
	p("// %s is a fluent shaped-read builder for %q. Conditions AND together.", q, t.SQLName)
	p("type %s struct {", q)
	p("\tv radclient.View")
	p("\tread protocol.Read")
	p("\tfilters []protocol.Expr")
	p("}")
	p("")

	emitFilterMethods(p, t, q, "q", "q.filters = append(q.filters, %s)")
	emitOrderMethods(p, t, q)

	p("func (q *%s) Limit(n int) *%s { q.read.Limit = n; return q }", q, q)
	p("func (q *%s) Offset(n int) *%s { q.read.Offset = n; return q }", q, q)
	p("")

	emitIncludeMethods(p, t, q, "q.read.Include = append(q.read.Include, inc)")

	p("// All executes the query.")
	p("func (q *%s) All(ctx context.Context) ([]%s, error) {", q, t.Model)
	p("\tq.read.Filter = andExpr(q.filters)")
	p("\trecs, err := q.v.Query(ctx, q.read)")
	p("\tif err != nil {")
	p("\t\treturn nil, err")
	p("\t}")
	p("\tout := make([]%s, len(recs))", t.Model)
	p("\tfor i, r := range recs {")
	p("\t\tout[i] = %sFromRecord(r)", lowerFirst(t.Model))
	p("\t}")
	p("\treturn out, nil")
	p("}")
	p("")
	p("// First executes the query with limit 1.")
	p("func (q *%s) First(ctx context.Context) (%s, bool, error) {", q, t.Model)
	p("\tq.read.Limit = 1")
	p("\trows, err := q.All(ctx)")
	p("\tif err != nil || len(rows) == 0 {")
	p("\t\treturn %s{}, false, err", t.Model)
	p("\t}")
	p("\treturn rows[0], true, nil")
	p("}")
	p("")

	emitAggregates(p, t, q)
}

// emitAggregates writes the terminal fold methods on the query builder. They
// reuse the builder's filter but drop ordering/pagination/includes, which are
// meaningless for a fold (and rejected by the server). Count is non-null;
// sum/avg/min/max return a pointer that is nil when no rows matched.
func emitAggregates(p func(string, ...any), t *genTable, q string) {
	// Shared runner: send the accumulated filter with the given fold terms and
	// return the single scalar record.
	p("// fold sends the builder's filter as an aggregate query and returns the")
	p("// one scalar record the server produces.")
	p("func (q *%s) fold(ctx context.Context, aggs []protocol.Agg) (protocol.Record, error) {", q)
	p("\tread := q.read")
	p("\tread.Filter = andExpr(q.filters)")
	p("\tread.OrderBy, read.Include, read.Limit, read.Offset = nil, nil, 0, 0")
	p("\tread.Aggs = aggs")
	p("\trecs, err := q.v.Query(ctx, read)")
	p("\tif err != nil || len(recs) == 0 {")
	p("\t\treturn protocol.Record{}, err")
	p("\t}")
	p("\treturn recs[0], nil")
	p("}")
	p("")

	// Count is always available and never NULL.
	p("// Count returns how many rows match (never NULL: 0 when none).")
	p("func (q *%s) Count(ctx context.Context) (int64, error) {", q)
	p("\trec, err := q.fold(ctx, []protocol.Agg{{Fn: \"count\", As: \"v\"}})")
	p("\tif err != nil {")
	p("\t\treturn 0, err")
	p("\t}")
	p("\treturn recInt64(rec, \"v\"), nil")
	p("}")
	p("")

	fold := func(method, fn, col, retType, helper, doc string) {
		p("// %s", doc)
		p("func (q *%s) %s(ctx context.Context) (%s, error) {", q, method, retType)
		p("\trec, err := q.fold(ctx, []protocol.Agg{{Fn: %q, Column: %q, As: \"v\"}})", fn, col)
		p("\tif err != nil {")
		p("\t\treturn nil, err")
		p("\t}")
		p("\treturn %s(rec, \"v\"), nil", helper)
		p("}")
		p("")
	}

	for _, c := range t.Cols {
		numeric := c.Type == "int64" || c.Type == "float64"
		ptrHelper := "rec" + goHelper(c.GoType) + "Ptr"
		if numeric {
			fold("Sum"+c.Field, "sum", c.SQLName, "*"+c.GoType, ptrHelper,
				fmt.Sprintf("Sum%s totals %q over matching rows (nil when none).", c.Field, c.SQLName))
			fold("Avg"+c.Field, "avg", c.SQLName, "*float64", "recFloat64Ptr",
				fmt.Sprintf("Avg%s averages %q (nil when none).", c.Field, c.SQLName))
		}
		fold("Min"+c.Field, "min", c.SQLName, "*"+c.GoType, ptrHelper,
			fmt.Sprintf("Min%s is the smallest %q over matching rows (nil when none).", c.Field, c.SQLName))
		fold("Max"+c.Field, "max", c.SQLName, "*"+c.GoType, ptrHelper,
			fmt.Sprintf("Max%s is the largest %q over matching rows (nil when none).", c.Field, c.SQLName))
	}
}

// emitFilterMethods writes typed column predicates onto builder type q with
// receiver recv; appendStmt is a printf pattern receiving the expression.
func emitFilterMethods(p func(string, ...any), t *genTable, q, recv, appendStmt string) {
	add := func(sig, expr string) {
		p("func (%s *%s) %s *%s {", recv, q, sig, q)
		p("\t"+appendStmt, expr)
		p("\treturn %s", recv)
		p("}")
	}
	for _, c := range t.Cols {
		add(fmt.Sprintf("%sEq(v %s)", c.Field, c.GoType),
			fmt.Sprintf("protocol.Expr{Op: \"eq\", Column: %q, Value: v}", c.SQLName))
		add(fmt.Sprintf("%sNe(v %s)", c.Field, c.GoType),
			fmt.Sprintf("protocol.Expr{Op: \"ne\", Column: %q, Value: v}", c.SQLName))
		if c.Type != "bool" {
			for _, op := range []struct{ suffix, op string }{
				{"Lt", "lt"}, {"Lte", "lte"}, {"Gt", "gt"}, {"Gte", "gte"},
			} {
				add(fmt.Sprintf("%s%s(v %s)", c.Field, op.suffix, c.GoType),
					fmt.Sprintf("protocol.Expr{Op: %q, Column: %q, Value: v}", op.op, c.SQLName))
			}
		}
		if c.Nullable {
			add(fmt.Sprintf("%sNull()", c.Field),
				fmt.Sprintf("protocol.Expr{Op: \"is_null\", Column: %q}", c.SQLName))
			add(fmt.Sprintf("%sNotNull()", c.Field),
				fmt.Sprintf("protocol.Expr{Op: \"not\", Expr: &protocol.Expr{Op: \"is_null\", Column: %q}}", c.SQLName))
		}
	}
	p("")
}

func emitOrderMethods(p func(string, ...any), t *genTable, q string) {
	for _, c := range t.Cols {
		p("func (q *%s) OrderBy%s() *%s {", q, c.Field, q)
		p("\tq.read.OrderBy = append(q.read.OrderBy, protocol.Order{Column: %q})", c.SQLName)
		p("\treturn q")
		p("}")
		p("func (q *%s) OrderBy%sDesc() *%s {", q, c.Field, q)
		p("\tq.read.OrderBy = append(q.read.OrderBy, protocol.Order{Column: %q, Desc: true})", c.SQLName)
		p("\treturn q")
		p("}")
	}
	p("")
}

// emitIncludeMethods writes Include* methods for both relation directions.
func emitIncludeMethods(p func(string, ...any), t *genTable, q, appendStmt string) {
	for _, r := range t.Forward {
		p("// Include%s embeds the referenced %s (nil when the FK is NULL).", r.Field, r.Target.Model)
		p("func (q *%s) Include%s(opts ...func(*%sInclude)) *%s {", q, r.Field, r.Target.Model, q)
		p("\tb := &%sInclude{inc: protocol.Include{FK: %q, Dir: \"parent\", As: %q}}", r.Target.Model, r.FKName, r.As)
		p("\tfor _, o := range opts {")
		p("\t\to(b)")
		p("\t}")
		p("\tinc := b.inc")
		p("\t" + appendStmt)
		p("\treturn q")
		p("}")
	}
	for _, r := range t.Reverse {
		p("// Include%s embeds the %s rows referencing this row.", r.Field, r.Target.Model)
		p("func (q *%s) Include%s(opts ...func(*%sInclude)) *%s {", q, r.Field, r.Target.Model, q)
		p("\tb := &%sInclude{inc: protocol.Include{FK: %q, Dir: \"children\", As: %q}}", r.Target.Model, r.FKName, r.As)
		p("\tfor _, o := range opts {")
		p("\t\to(b)")
		p("\t}")
		p("\tb.inc.Filter = andExpr(b.filters)")
		p("\tinc := b.inc")
		p("\t" + appendStmt)
		p("\treturn q")
		p("}")
	}
	p("")
}

// emitInclude writes the include builder used to refine child fetches
// (filter, order, limit, nested includes).
func emitInclude(p func(string, ...any), t *genTable) {
	q := t.Model + "Include"
	p("// %s refines an included %q fetch.", q, t.SQLName)
	p("type %s struct {", q)
	p("\tinc protocol.Include")
	p("\tfilters []protocol.Expr")
	p("}")
	p("")

	emitFilterMethods(p, t, q, "b", "b.filters = append(b.filters, %s)")

	for _, c := range t.Cols {
		p("func (b *%s) OrderBy%s() *%s {", q, c.Field, q)
		p("\tb.inc.OrderBy = append(b.inc.OrderBy, protocol.Order{Column: %q})", c.SQLName)
		p("\treturn b")
		p("}")
		p("func (b *%s) OrderBy%sDesc() *%s {", q, c.Field, q)
		p("\tb.inc.OrderBy = append(b.inc.OrderBy, protocol.Order{Column: %q, Desc: true})", c.SQLName)
		p("\treturn b")
		p("}")
	}
	p("func (b *%s) Limit(n int) *%s { b.inc.Limit = n; return b }", q, q)
	p("")

	// Nested includes on include builders.
	for _, r := range t.Forward {
		p("func (b *%s) Include%s(opts ...func(*%sInclude)) *%s {", q, r.Field, r.Target.Model, q)
		p("\tnested := &%sInclude{inc: protocol.Include{FK: %q, Dir: \"parent\", As: %q}}", r.Target.Model, r.FKName, r.As)
		p("\tfor _, o := range opts {")
		p("\t\to(nested)")
		p("\t}")
		p("\tb.inc.Include = append(b.inc.Include, nested.inc)")
		p("\treturn b")
		p("}")
	}
	for _, r := range t.Reverse {
		p("func (b *%s) Include%s(opts ...func(*%sInclude)) *%s {", q, r.Field, r.Target.Model, q)
		p("\tnested := &%sInclude{inc: protocol.Include{FK: %q, Dir: \"children\", As: %q}}", r.Target.Model, r.FKName, r.As)
		p("\tfor _, o := range opts {")
		p("\t\to(nested)")
		p("\t}")
		p("\tnested.inc.Filter = andExpr(nested.filters)")
		p("\tb.inc.Include = append(b.inc.Include, nested.inc)")
		p("\treturn b")
		p("}")
	}
	p("")
}

// emitConverters writes protocol.Record → model decoding.
func emitConverters(p func(string, ...any), t *genTable) {
	fn := lowerFirst(t.Model)
	p("func %sFromRecord(rec protocol.Record) %s {", fn, t.Model)
	p("\tm := %s{}", t.Model)
	for _, c := range t.Cols {
		helper := "rec" + goHelper(c.GoType)
		if c.Nullable {
			helper += "Ptr"
		}
		p("\tm.%s = %s(rec, %q)", c.Field, helper, c.SQLName)
	}
	for _, r := range t.Forward {
		p("\tif parent, ok := rec[%q].(map[string]any); ok {", r.As)
		p("\t\tv := %sFromRecord(parent)", lowerFirst(r.Target.Model))
		p("\t\tm.%s = &v", r.Field)
		p("\t}")
	}
	for _, r := range t.Reverse {
		p("\tif kids, ok := rec[%q].([]any); ok {", r.As)
		p("\t\tfor _, k := range kids {")
		p("\t\t\tif child, ok := k.(map[string]any); ok {")
		p("\t\t\t\tm.%s = append(m.%s, %sFromRecord(child))", r.Field, r.Field, lowerFirst(r.Target.Model))
		p("\t\t\t}")
		p("\t\t}")
		p("\t}")
	}
	p("\treturn m")
	p("}")
	p("")
}

func goHelper(goType string) string {
	switch goType {
	case "string":
		return "String"
	case "int64":
		return "Int64"
	case "float64":
		return "Float64"
	case "bool":
		return "Bool"
	}
	return "String"
}
