package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"

	"github.com/Southclaws/rad/cmd/rad/config"
	"github.com/Southclaws/rad/rad/codegen"
	catalogschema "github.com/Southclaws/rad/rad/engine/02_catalog/schema"
	projectstate "github.com/Southclaws/rad/rad/state"
)

const acceptedSchemaFixture = `
tables:
  - id: 1
    name: users
    columns:
      - { id: 1, name: id, type: string, pk: true }
`

func TestGenerateOneUsesAcceptedIdentity(t *testing.T) {
	directory := t.TempDir()
	desired := filepath.Join(directory, config.DefaultSchemaFile)
	if err := os.WriteFile(desired, []byte(acceptedSchemaFixture), 0o600); err != nil {
		t.Fatal(err)
	}
	accepted := acceptedFixture(t, 4)
	if err := generateOne(&cobra.Command{}, desired, filepath.Join(directory, "generated"), "db", "go", accepted); err != nil {
		t.Fatal(err)
	}
	generated, err := os.ReadFile(filepath.Join(directory, "generated", codegen.GoClientFilename))
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range []string{"SchemaVersion uint64 = 4", accepted.Lock.SchemaHash, "const RawSchema"} {
		if !strings.Contains(string(generated), expected) {
			t.Errorf("generated client missing %q", expected)
		}
	}
}

func TestGenerateOneRemovesOnlySupersededRadGoClients(t *testing.T) {
	directory := t.TempDir()
	desired := filepath.Join(directory, config.DefaultSchemaFile)
	if err := os.WriteFile(desired, []byte(acceptedSchemaFixture), 0o600); err != nil {
		t.Fatal(err)
	}
	output := filepath.Join(directory, "generated")
	if err := os.MkdirAll(output, 0o755); err != nil {
		t.Fatal(err)
	}
	old := filepath.Join(output, "db.go")
	if err := os.WriteFile(old, []byte("// Code generated by rad generate. DO NOT EDIT.\npackage db\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	handwritten := filepath.Join(output, "helpers.go")
	if err := os.WriteFile(handwritten, []byte("package db\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := generateOne(&cobra.Command{}, desired, output, "db", "go", acceptedFixture(t, 4)); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(old); !os.IsNotExist(err) {
		t.Fatalf("superseded generated file still exists: %v", err)
	}
	if _, err := os.Stat(handwritten); err != nil {
		t.Fatalf("handwritten Go file was removed: %v", err)
	}
}

func TestGenerateOneRemovesOnlySupersededRadTypeScriptClients(t *testing.T) {
	directory := t.TempDir()
	desired := filepath.Join(directory, config.DefaultSchemaFile)
	if err := os.WriteFile(desired, []byte(acceptedSchemaFixture), 0o600); err != nil {
		t.Fatal(err)
	}
	output := filepath.Join(directory, "generated")
	if err := os.MkdirAll(output, 0o755); err != nil {
		t.Fatal(err)
	}
	old := filepath.Join(output, "db.ts")
	if err := os.WriteFile(old, []byte("// Code generated by rad generate. DO NOT EDIT.\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	handwritten := filepath.Join(output, "helpers.ts")
	if err := os.WriteFile(handwritten, []byte("export const helper = true;\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := generateOne(&cobra.Command{}, desired, output, "db", "ts", acceptedFixture(t, 4)); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(old); !os.IsNotExist(err) {
		t.Fatalf("superseded generated file still exists: %v", err)
	}
	if _, err := os.Stat(handwritten); err != nil {
		t.Fatalf("handwritten TypeScript file was removed: %v", err)
	}
	if _, err := os.Stat(filepath.Join(output, codegen.TypeScriptClientFilename)); err != nil {
		t.Fatalf("fixed TypeScript client was not generated: %v", err)
	}
}

func TestGenerateOneRefusesUnappliedDesiredSchema(t *testing.T) {
	directory := t.TempDir()
	desired := filepath.Join(directory, config.DefaultSchemaFile)
	modified := strings.Replace(acceptedSchemaFixture, "users", "accounts", 1)
	if err := os.WriteFile(desired, []byte(modified), 0o600); err != nil {
		t.Fatal(err)
	}
	err := generateOne(&cobra.Command{}, desired, filepath.Join(directory, "generated"), "db", "go", acceptedFixture(t, 4))
	if err == nil || !strings.Contains(err.Error(), "rad schema migrate") {
		t.Fatalf("error = %v", err)
	}
}

func acceptedFixture(t *testing.T, version uint64) projectstate.Accepted {
	t.Helper()
	parsed, err := catalogschema.Parse("accepted.rad.schema.yaml", []byte(acceptedSchemaFixture))
	if err != nil {
		t.Fatal(err)
	}
	canonical := parsed.Canonical()
	hash, err := canonical.Hash()
	if err != nil {
		t.Fatal(err)
	}
	return projectstate.Accepted{
		Lock:   projectstate.Lock{FormatVersion: projectstate.FormatVersion, SchemaVersion: version, SchemaHash: hash},
		Source: []byte(acceptedSchemaFixture), Schema: canonical,
	}
}
