// GENERATED by keyform from protocol/storage.keyform. Do not edit.
// Regenerate with `task generate:storage`.

//! Human-readable rendering of durable storage keys for admin and
//! debug tooling. Built on the generated key parsers; carries no
//! compatibility promise.

use crate::engine::kv::keys;

pub fn describe_key(key: &[u8]) -> Option<String> {
    let rest = key.strip_prefix(keys::ROOT_MAGIC)?;
    let tag = *rest.first()?;
    match tag {
        keys::DATA_TAG => {
            let parts = keys::decode_data_key(key)?;
            Some(format!(
                "data/table=t{}/generation={}/primary_key=({})",
                parts.table,
                parts.generation,
                tuple_text(&parts.primary_key)
            ))
        }
        keys::INDEX_TAG => {
            let parts = keys::decode_index_key(key)?;
            Some(format!(
                "index/table=t{}/index=i{}/tuple_rest=({})",
                parts.table,
                parts.index,
                tuple_text(&parts.tuple_rest)
            ))
        }
        keys::CATALOG_TABLE_OBJECT_TAG => {
            let parts = keys::decode_catalog_table_object_key(key)?;
            Some(format!(
                "catalog_table_object/schema={}/generation={}",
                parts.schema, parts.generation
            ))
        }
        keys::CATALOG_TABLE_HEAD_TAG => {
            let parts = keys::decode_catalog_table_head_key(key)?;
            Some(format!("catalog_table_head/schema={}", parts.schema))
        }
        keys::CATALOG_TABLE_TAG => {
            let parts = keys::decode_catalog_table_key(key)?;
            Some(format!("catalog_table/table=t{}", parts.table))
        }
        keys::CATALOG_TABLE_NAME_TAG => {
            let parts = keys::decode_catalog_table_name_key(key)?;
            Some(format!("catalog_table_name/name={:?}", parts.name))
        }
        keys::CATALOG_SCHEMA_REVISION_TAG => {
            let parts = keys::decode_catalog_schema_revision_key(key)?;
            Some(format!("catalog_schema_revision/version={}", parts.version))
        }
        keys::CATALOG_WRITE_PROTOCOL_OBJECT_TAG => {
            let parts = keys::decode_catalog_write_protocol_object_key(key)?;
            Some(format!(
                "catalog_write_protocol_object/table=t{}/generation={}",
                parts.table, parts.generation
            ))
        }
        keys::CATALOG_WRITE_PROTOCOL_FENCE_TAG => {
            let parts = keys::decode_catalog_write_protocol_fence_key(key)?;
            Some(format!(
                "catalog_write_protocol_fence/table=t{}",
                parts.table
            ))
        }
        keys::CATALOG_FENCE_TABLE_EXISTENCE_TAG => {
            let parts = keys::decode_catalog_fence_table_existence_key(key)?;
            Some(format!(
                "catalog_fence_table_existence/table=t{}",
                parts.table
            ))
        }
        keys::CATALOG_FENCE_COLUMN_VALUE_TAG => {
            let parts = keys::decode_catalog_fence_column_value_key(key)?;
            Some(format!(
                "catalog_fence_column_value/table=t{}/column=c{}",
                parts.table, parts.column
            ))
        }
        keys::CATALOG_FENCE_INDEX_ACCESS_TAG => {
            let parts = keys::decode_catalog_fence_index_access_key(key)?;
            Some(format!(
                "catalog_fence_index_access/table=t{}/index=i{}",
                parts.table, parts.index
            ))
        }
        keys::CATALOG_TRANSITION_TAG => {
            let parts = keys::decode_catalog_transition_key(key)?;
            Some(format!(
                "catalog_transition/transition=tr{}",
                parts.transition
            ))
        }
        keys::CATALOG_TRANSITION_DELTA_TAG => {
            let parts = keys::decode_catalog_transition_delta_key(key)?;
            Some(format!(
                "catalog_transition_delta/transition=tr{}/sequence={}",
                parts.transition, parts.sequence
            ))
        }
        keys::CATALOG_TRANSITION_DELTA_SEQUENCE_TAG => {
            let parts = keys::decode_catalog_transition_delta_sequence_key(key)?;
            Some(format!(
                "catalog_transition_delta_sequence/transition=tr{}",
                parts.transition
            ))
        }
        keys::CATALOG_TRANSITION_DELTA_APPLIED_TAG => {
            let parts = keys::decode_catalog_transition_delta_applied_key(key)?;
            Some(format!(
                "catalog_transition_delta_applied/transition=tr{}",
                parts.transition
            ))
        }
        keys::CATALOG_TRANSITION_UNIQUE_CLAIM_TAG => {
            let parts = keys::decode_catalog_transition_unique_claim_key(key)?;
            Some(format!(
                "catalog_transition_unique_claim/transition=tr{}/indexed=0x{}/primary_key=0x{}",
                parts.transition,
                hex_text(&parts.indexed),
                hex_text(&parts.primary_key)
            ))
        }
        keys::CATALOG_TRANSITION_UNIQUE_VIOLATION_TAG => {
            let parts = keys::decode_catalog_transition_unique_violation_key(key)?;
            Some(format!(
                "catalog_transition_unique_violation/transition=tr{}/indexed=0x{}",
                parts.transition,
                hex_text(&parts.indexed)
            ))
        }
        keys::CATALOG_TRANSITION_VIOLATION_TAG => {
            let parts = keys::decode_catalog_transition_violation_key(key)?;
            Some(format!(
                "catalog_transition_violation/transition=tr{}/row_identity=0x{}",
                parts.transition,
                hex_text(&parts.row_identity)
            ))
        }
        keys::CATALOG_RETENTION_PIN_TAG => {
            let parts = keys::decode_catalog_retention_pin_key(key)?;
            Some(format!("catalog_retention_pin/pin={:?}", parts.pin))
        }
        keys::CATALOG_RECLAMATION_TAG => {
            let parts = keys::decode_catalog_reclamation_key(key)?;
            Some(format!(
                "catalog_reclamation/reclamation={:?}",
                parts.reclamation
            ))
        }
        keys::CATALOG_META_MODE_TAG => (rest.len() == 1).then(|| "catalog_meta_mode".to_owned()),
        keys::CATALOG_META_NEXT_ID_TAG => {
            (rest.len() == 1).then(|| "catalog_meta_next_id".to_owned())
        }
        keys::CATALOG_META_SCHEMA_VERSION_TAG => {
            (rest.len() == 1).then(|| "catalog_meta_schema_version".to_owned())
        }
        keys::CATALOG_META_CATALOG_GENERATION_TAG => {
            (rest.len() == 1).then(|| "catalog_meta_catalog_generation".to_owned())
        }
        keys::CATALOG_META_COMPACTED_THROUGH_TAG => {
            (rest.len() == 1).then(|| "catalog_meta_compacted_through".to_owned())
        }
        keys::CATALOG_META_TRANSITION_SEEN_TAG => {
            (rest.len() == 1).then(|| "catalog_meta_transition_seen".to_owned())
        }
        keys::CATALOG_META_RECLAMATION_SEEN_TAG => {
            (rest.len() == 1).then(|| "catalog_meta_reclamation_seen".to_owned())
        }
        keys::RUNTIME_WRITER_FENCE_TAG => {
            (rest.len() == 1).then(|| "runtime_writer_fence".to_owned())
        }
        keys::STORAGE_MANIFEST_TAG => (rest.len() == 1).then(|| "storage_manifest".to_owned()),
        _ => None,
    }
}

/// Scalar tuples render through the production decoder, falling back to
/// hex when the bytes are not a valid tuple.
fn tuple_text(bytes: &[u8]) -> String {
    if bytes.is_empty() {
        return String::new();
    }
    match super::codec::decode_tuple(bytes) {
        Ok(values) => values
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", "),
        Err(_) => format!("0x{}", hex_text(bytes)),
    }
}

fn hex_text(bytes: &[u8]) -> String {
    use std::fmt::Write as _;
    let mut hex = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        let _ = write!(hex, "{byte:02x}");
    }
    hex
}
