// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetHealth implements GetHealth operation.
//
// A cheap liveness probe that touches no storage. It always returns `200` with a small status body
// while the process is serving, so it is safe to use as a readiness check or a `rad://` reachability
// test before opening a connection.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *Health, _ error) {
	return r, ht.ErrNotImplemented
}

// Query implements Query operation.
//
// Execute a single-consumer relation tree encoded as named relation nodes — scans, filters,
// projections, joins, aggregates, ordering, slicing — plus a root selector. Relationships need no
// dedicated verb: a projection field whose expression is a cardinality crossing (`exists`, `first`,
// `scalar`, `array`) materialises a correlated sub-relation as a nested boolean, object, value, or
// array. Aggregation is the `aggregate` node, grouped or global, and rides this one operation.
//
// The result is one datum, shaped exactly as the root materialises: `many` yields an array of records,
// `first` a record or `null`, `exactly_one` a record (erroring unless exactly one row exists), and
// `scalar` a naked value or `null`.
//
// The tree is structurally validated before binding. Unknown fields, cyclic, dangling, shared, or
// unreachable node definitions are invalid. Binding then rejects unknown tables, columns, or scopes,
// type mismatches, and nondeterministic crossings (a `first` over an unordered multi-row relation).
// Root `scalar` additionally requires one column and a statically at-most-one relation.
//
// POST /query
func (UnimplementedHandler) Query(ctx context.Context, req Query) (r QueryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RowCreate implements RowCreate operation.
//
// Insert a single row into a table. Columns left out of `values` fall back to their schema default, so
// generated defaults such as `uuid()` and `now_ms()` are filled in server side. The complete stored
// row, including any generated values, is returned.
//
// Inserting a row that would violate a unique constraint, or whose foreign key references a row that
// does not exist, fails with a `conflict` problem and nothing is written.
//
// POST /create
func (UnimplementedHandler) RowCreate(ctx context.Context, req OptRowCreateProps) (r RowCreateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RowDelete implements RowDelete operation.
//
// Delete the row named by `key`. The response reports whether a row was actually removed through
// `found`. Deleting a row that does not exist is not an error and reports `found` as `false`.
//
// A delete that would leave a dangling foreign key reference is refused with a `conflict` problem,
// since Rad restricts rather than cascades.
//
// POST /delete
func (UnimplementedHandler) RowDelete(ctx context.Context, req OptRowDeleteProps) (r RowDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RowUpdate implements RowUpdate operation.
//
// Update the row named by `key`. Columns in `set` are assigned new values; columns listed in `clear`
// are set to `null` (only nullable columns may be cleared). Columns mentioned in neither are left as
// they are.
//
// When the target row exists the updated record is returned with `found` set to `true`. When it does
// not exist, `found` is `false` and nothing is written. Violating a unique constraint fails with a
// `conflict` problem.
//
// POST /update
func (UnimplementedHandler) RowUpdate(ctx context.Context, req OptRowUpdateProps) (r RowUpdateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SchemaMigrate implements SchemaMigrate operation.
//
// Take a `schema.rad` source document, compute the difference against the database's current catalog,
// and apply whatever changes are needed to make them match. The response lists the steps that were
// applied, in order.
//
// Migration is idempotent. Submitting a schema that already matches the database applies nothing and
// returns an empty step list. Renames are driven by `renamed_from` hints in the schema so that
// renaming a column or table does not drop and recreate it.
//
// A schema that fails to parse or validate, or that requests an unsupported change (such as altering a
// column's type), is rejected with an `invalid` problem and the database is left untouched.
//
// POST /migrate
func (UnimplementedHandler) SchemaMigrate(ctx context.Context, req OptMigrateProps) (r SchemaMigrateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TableList implements TableList operation.
//
// Return every table currently defined in the catalog, along with its columns and primary key. This
// reflects the schema as it exists right now, after the most recent successful migration. An empty
// database returns an empty list, not an error.
//
// Use this to introspect a running server without access to the original `schema.rad` file.
//
// GET /tables
func (UnimplementedHandler) TableList(ctx context.Context) (r *TableList, _ error) {
	return r, ht.ErrNotImplemented
}

// TransactionBegin implements TransactionBegin operation.
//
// Start a server held serializable transaction and return an opaque transaction id. Subsequent reads
// and writes made under `/tx/{id}` see a consistent snapshot plus their own uncommitted writes, and
// are isolated from other transactions until committed.
//
// A transaction holds server side state, so it must be finished with either commit or rollback. An
// idle transaction is reaped automatically after roughly sixty seconds, after which its id is no
// longer valid.
//
// POST /tx
func (UnimplementedHandler) TransactionBegin(ctx context.Context) (r *TransactionCredentials, _ error) {
	return r, ht.ErrNotImplemented
}

// TransactionCommit implements TransactionCommit operation.
//
// Atomically apply every write staged in the transaction and release its server side state. On success
// the transaction id is spent and can no longer be used.
//
// If another transaction committed a conflicting change while this one was open, the commit fails with
// a `conflict` problem. The correct response is to open a fresh transaction and replay the work.
//
// POST /tx/{id}/commit
func (UnimplementedHandler) TransactionCommit(ctx context.Context, params TransactionCommitParams) (r TransactionCommitRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TransactionQuery implements TransactionQuery operation.
//
// Behaves exactly like `Query`, but reads through the transaction's snapshot and sees the
// transaction's own uncommitted writes. Referencing an unknown or already finished transaction fails
// with a `not_found` problem.
//
// POST /tx/{id}/query
func (UnimplementedHandler) TransactionQuery(ctx context.Context, req Query, params TransactionQueryParams) (r TransactionQueryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TransactionRollback implements TransactionRollback operation.
//
// Discard every write staged in the transaction and release its server side state. On success the
// transaction id is spent.
//
// Rolling back is safe to call defensively. A transaction that has already been committed or rolled
// back, or that has been reaped for being idle, is simply gone, so clients may treat a `not_found`
// here as success.
//
// POST /tx/{id}/rollback
func (UnimplementedHandler) TransactionRollback(ctx context.Context, params TransactionRollbackParams) (r TransactionRollbackRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TransactionRowCreate implements TransactionRowCreate operation.
//
// Behaves exactly like `RowCreate`, but the write is staged in the transaction and only becomes
// visible to others on commit. Referencing an unknown or already finished transaction fails with a
// `not_found` problem.
//
// POST /tx/{id}/create
func (UnimplementedHandler) TransactionRowCreate(ctx context.Context, req OptRowCreateProps, params TransactionRowCreateParams) (r TransactionRowCreateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TransactionRowDelete implements TransactionRowDelete operation.
//
// Behaves exactly like `RowDelete`, but the delete is staged in the transaction and only becomes
// visible to others on commit. Referencing an unknown or already finished transaction fails with a
// `not_found` problem.
//
// POST /tx/{id}/delete
func (UnimplementedHandler) TransactionRowDelete(ctx context.Context, req OptRowDeleteProps, params TransactionRowDeleteParams) (r TransactionRowDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TransactionRowUpdate implements TransactionRowUpdate operation.
//
// Behaves exactly like `RowUpdate`, but the write is staged in the transaction and only becomes
// visible to others on commit. Referencing an unknown or already finished transaction fails with a
// `not_found` problem.
//
// POST /tx/{id}/update
func (UnimplementedHandler) TransactionRowUpdate(ctx context.Context, req OptRowUpdateProps, params TransactionRowUpdateParams) (r TransactionRowUpdateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *InternalServerErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *InternalServerErrorStatusCode) {
	r = new(InternalServerErrorStatusCode)
	return r
}
