// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

func (s *InternalServerErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type ColumnCreateConflict Problem

func (*ColumnCreateConflict) columnCreateRes() {}

type ColumnCreateUnprocessableEntity Problem

func (*ColumnCreateUnprocessableEntity) columnCreateRes() {}

// A column default, applied when an insert omits the column: either a builtin generator named by
// `func` (`uuid` on text columns, `now_ms` on int64 columns) or a literal `value` of the column's
// type. Exactly one of the two is set.
// Ref: #/components/schemas/ColumnDefault
type ColumnDefault struct {
	// A builtin generator, `uuid` or `now_ms`.
	Func OptString `json:"func"`
	// A literal of the column's type.
	Value Value `json:"value"`
}

// GetFunc returns the value of Func.
func (s *ColumnDefault) GetFunc() OptString {
	return s.Func
}

// GetValue returns the value of Value.
func (s *ColumnDefault) GetValue() Value {
	return s.Value
}

// SetFunc sets the value of Func.
func (s *ColumnDefault) SetFunc(val OptString) {
	s.Func = val
}

// SetValue sets the value of Value.
func (s *ColumnDefault) SetValue(val Value) {
	s.Value = val
}

type ColumnDeleteConflict Problem

func (*ColumnDeleteConflict) columnDeleteRes() {}

type ColumnDeleteUnprocessableEntity Problem

func (*ColumnDeleteUnprocessableEntity) columnDeleteRes() {}

// One column of a table, as reported by introspection.
// Ref: #/components/schemas/ColumnInfo
type ColumnInfo struct {
	Name string `json:"name"`
	// The column's storage type, one of `text`, `int64`, `float64`, or `bool`.
	Type     string  `json:"type"`
	Nullable OptBool `json:"nullable"`
	// An optional semantic hint such as `uuid` or `unix_ms`.
	Format  OptString        `json:"format"`
	Default OptColumnDefault `json:"default"`
}

// GetName returns the value of Name.
func (s *ColumnInfo) GetName() string {
	return s.Name
}

// GetType returns the value of Type.
func (s *ColumnInfo) GetType() string {
	return s.Type
}

// GetNullable returns the value of Nullable.
func (s *ColumnInfo) GetNullable() OptBool {
	return s.Nullable
}

// GetFormat returns the value of Format.
func (s *ColumnInfo) GetFormat() OptString {
	return s.Format
}

// GetDefault returns the value of Default.
func (s *ColumnInfo) GetDefault() OptColumnDefault {
	return s.Default
}

// SetName sets the value of Name.
func (s *ColumnInfo) SetName(val string) {
	s.Name = val
}

// SetType sets the value of Type.
func (s *ColumnInfo) SetType(val string) {
	s.Type = val
}

// SetNullable sets the value of Nullable.
func (s *ColumnInfo) SetNullable(val OptBool) {
	s.Nullable = val
}

// SetFormat sets the value of Format.
func (s *ColumnInfo) SetFormat(val OptString) {
	s.Format = val
}

// SetDefault sets the value of Default.
func (s *ColumnInfo) SetDefault(val OptColumnDefault) {
	s.Default = val
}

type ColumnUpdateConflict Problem

func (*ColumnUpdateConflict) columnUpdateRes() {}

// The column properties to update.
// Ref: #/components/schemas/ColumnUpdateProps
type ColumnUpdateProps struct {
	// The column's new name.
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *ColumnUpdateProps) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *ColumnUpdateProps) SetName(val string) {
	s.Name = val
}

type ColumnUpdateUnprocessableEntity Problem

func (*ColumnUpdateUnprocessableEntity) columnUpdateRes() {}

// Stable metadata about a Rad database.
// Ref: #/components/schemas/DatabaseInfo
type DatabaseInfo struct {
	// The database's catalog management mode: `direct` (the catalog is mutable over this API) or `schema`
	// (schema.rad migrations own the catalog and the imperative catalog operations are rejected).
	Mode DatabaseInfoMode `json:"mode"`
	// The configured backing-store location, when the server exposes one.
	Location OptString `json:"location"`
}

// GetMode returns the value of Mode.
func (s *DatabaseInfo) GetMode() DatabaseInfoMode {
	return s.Mode
}

// GetLocation returns the value of Location.
func (s *DatabaseInfo) GetLocation() OptString {
	return s.Location
}

// SetMode sets the value of Mode.
func (s *DatabaseInfo) SetMode(val DatabaseInfoMode) {
	s.Mode = val
}

// SetLocation sets the value of Location.
func (s *DatabaseInfo) SetLocation(val OptString) {
	s.Location = val
}

// The database's catalog management mode: `direct` (the catalog is mutable over this API) or `schema`
// (schema.rad migrations own the catalog and the imperative catalog operations are rejected).
type DatabaseInfoMode string

const (
	DatabaseInfoModeDirect DatabaseInfoMode = "direct"
	DatabaseInfoModeSchema DatabaseInfoMode = "schema"
)

// AllValues returns all DatabaseInfoMode values.
func (DatabaseInfoMode) AllValues() []DatabaseInfoMode {
	return []DatabaseInfoMode{
		DatabaseInfoModeDirect,
		DatabaseInfoModeSchema,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DatabaseInfoMode) MarshalText() ([]byte, error) {
	switch s {
	case DatabaseInfoModeDirect:
		return []byte(s), nil
	case DatabaseInfoModeSchema:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DatabaseInfoMode) UnmarshalText(data []byte) error {
	switch DatabaseInfoMode(data) {
	case DatabaseInfoModeDirect:
		*s = DatabaseInfoModeDirect
		return nil
	case DatabaseInfoModeSchema:
		*s = DatabaseInfoModeSchema
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ExecuteBadRequest Problem

func (*ExecuteBadRequest) executeRes() {}

type ExecuteConflict Problem

func (*ExecuteConflict) executeRes() {}

type ExecuteUnprocessableEntity Problem

func (*ExecuteUnprocessableEntity) executeRes() {}

// One foreign key, in both definitions and introspection. The referenced columns must be the
// referenced table's full primary key.
// Ref: #/components/schemas/ForeignKeyInfo
type ForeignKeyInfo struct {
	Name string `json:"name"`
	// The referencing column names on this table.
	Columns []string `json:"columns"`
	// The referenced table's name.
	RefTable string `json:"ref_table"`
	// The referenced table's primary key columns, in order.
	RefColumns []string `json:"ref_columns"`
}

// GetName returns the value of Name.
func (s *ForeignKeyInfo) GetName() string {
	return s.Name
}

// GetColumns returns the value of Columns.
func (s *ForeignKeyInfo) GetColumns() []string {
	return s.Columns
}

// GetRefTable returns the value of RefTable.
func (s *ForeignKeyInfo) GetRefTable() string {
	return s.RefTable
}

// GetRefColumns returns the value of RefColumns.
func (s *ForeignKeyInfo) GetRefColumns() []string {
	return s.RefColumns
}

// SetName sets the value of Name.
func (s *ForeignKeyInfo) SetName(val string) {
	s.Name = val
}

// SetColumns sets the value of Columns.
func (s *ForeignKeyInfo) SetColumns(val []string) {
	s.Columns = val
}

// SetRefTable sets the value of RefTable.
func (s *ForeignKeyInfo) SetRefTable(val string) {
	s.RefTable = val
}

// SetRefColumns sets the value of RefColumns.
func (s *ForeignKeyInfo) SetRefColumns(val []string) {
	s.RefColumns = val
}

// The liveness status of the server.
// Ref: #/components/schemas/Health
type Health struct {
	Status string `json:"status"`
	// The database's catalog management mode: `direct` (the catalog is mutable over this API) or `schema`
	// (schema.rad migrations own the catalog and the imperative catalog operations are rejected).
	Mode string `json:"mode"`
}

// GetStatus returns the value of Status.
func (s *Health) GetStatus() string {
	return s.Status
}

// GetMode returns the value of Mode.
func (s *Health) GetMode() string {
	return s.Mode
}

// SetStatus sets the value of Status.
func (s *Health) SetStatus(val string) {
	s.Status = val
}

// SetMode sets the value of Mode.
func (s *Health) SetMode(val string) {
	s.Mode = val
}

type IndexCreateConflict Problem

func (*IndexCreateConflict) indexCreateRes() {}

type IndexCreateUnprocessableEntity Problem

func (*IndexCreateUnprocessableEntity) indexCreateRes() {}

type IndexDeleteConflict Problem

func (*IndexDeleteConflict) indexDeleteRes() {}

type IndexDeleteUnprocessableEntity Problem

func (*IndexDeleteUnprocessableEntity) indexDeleteRes() {}

// One secondary index, in both definitions and introspection.
// Ref: #/components/schemas/IndexInfo
type IndexInfo struct {
	Name string `json:"name"`
	// The indexed column names, in order.
	Columns []string `json:"columns"`
	Unique  OptBool  `json:"unique"`
}

// GetName returns the value of Name.
func (s *IndexInfo) GetName() string {
	return s.Name
}

// GetColumns returns the value of Columns.
func (s *IndexInfo) GetColumns() []string {
	return s.Columns
}

// GetUnique returns the value of Unique.
func (s *IndexInfo) GetUnique() OptBool {
	return s.Unique
}

// SetName sets the value of Name.
func (s *IndexInfo) SetName(val string) {
	s.Name = val
}

// SetColumns sets the value of Columns.
func (s *IndexInfo) SetColumns(val []string) {
	s.Columns = val
}

// SetUnique sets the value of Unique.
func (s *IndexInfo) SetUnique(val OptBool) {
	s.Unique = val
}

// InternalServerErrorStatusCode wraps Problem with StatusCode.
type InternalServerErrorStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *InternalServerErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *InternalServerErrorStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *InternalServerErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *InternalServerErrorStatusCode) SetResponse(val Problem) {
	s.Response = val
}

// A request to reconcile the database with a schema.
// Ref: #/components/schemas/MigrateProps
type MigrateProps struct {
	// The full `schema.rad` source document, as YAML.
	Schema string `json:"schema"`
}

// GetSchema returns the value of Schema.
func (s *MigrateProps) GetSchema() string {
	return s.Schema
}

// SetSchema sets the value of Schema.
func (s *MigrateProps) SetSchema(val string) {
	s.Schema = val
}

// The outcome of a migration.
// Ref: #/components/schemas/MigrateResult
type MigrateResult struct {
	// A human readable description of each change that was applied, in the order it was applied. Empty
	// when the database already matched.
	Steps []string `json:"steps"`
}

// GetSteps returns the value of Steps.
func (s *MigrateResult) GetSteps() []string {
	return s.Steps
}

// SetSteps sets the value of Steps.
func (s *MigrateResult) SetSteps(val []string) {
	s.Steps = val
}

func (*MigrateResult) schemaMigrateRes() {}

// Ref: #/components/responses/NoContent
type NoContent struct{}

func (*NoContent) tableDeleteRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptColumnDefault returns new OptColumnDefault with value set to v.
func NewOptColumnDefault(v ColumnDefault) OptColumnDefault {
	return OptColumnDefault{
		Value: v,
		Set:   true,
	}
}

// OptColumnDefault is optional ColumnDefault.
type OptColumnDefault struct {
	Value ColumnDefault
	Set   bool
}

// IsSet returns true if OptColumnDefault was set.
func (o OptColumnDefault) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptColumnDefault) Reset() {
	var v ColumnDefault
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptColumnDefault) SetTo(v ColumnDefault) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptColumnDefault) Get() (v ColumnDefault, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptColumnDefault) Or(d ColumnDefault) ColumnDefault {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptColumnInfo returns new OptColumnInfo with value set to v.
func NewOptColumnInfo(v ColumnInfo) OptColumnInfo {
	return OptColumnInfo{
		Value: v,
		Set:   true,
	}
}

// OptColumnInfo is optional ColumnInfo.
type OptColumnInfo struct {
	Value ColumnInfo
	Set   bool
}

// IsSet returns true if OptColumnInfo was set.
func (o OptColumnInfo) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptColumnInfo) Reset() {
	var v ColumnInfo
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptColumnInfo) SetTo(v ColumnInfo) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptColumnInfo) Get() (v ColumnInfo, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptColumnInfo) Or(d ColumnInfo) ColumnInfo {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptColumnUpdateProps returns new OptColumnUpdateProps with value set to v.
func NewOptColumnUpdateProps(v ColumnUpdateProps) OptColumnUpdateProps {
	return OptColumnUpdateProps{
		Value: v,
		Set:   true,
	}
}

// OptColumnUpdateProps is optional ColumnUpdateProps.
type OptColumnUpdateProps struct {
	Value ColumnUpdateProps
	Set   bool
}

// IsSet returns true if OptColumnUpdateProps was set.
func (o OptColumnUpdateProps) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptColumnUpdateProps) Reset() {
	var v ColumnUpdateProps
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptColumnUpdateProps) SetTo(v ColumnUpdateProps) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptColumnUpdateProps) Get() (v ColumnUpdateProps, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptColumnUpdateProps) Or(d ColumnUpdateProps) ColumnUpdateProps {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptIndexInfo returns new OptIndexInfo with value set to v.
func NewOptIndexInfo(v IndexInfo) OptIndexInfo {
	return OptIndexInfo{
		Value: v,
		Set:   true,
	}
}

// OptIndexInfo is optional IndexInfo.
type OptIndexInfo struct {
	Value IndexInfo
	Set   bool
}

// IsSet returns true if OptIndexInfo was set.
func (o OptIndexInfo) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptIndexInfo) Reset() {
	var v IndexInfo
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptIndexInfo) SetTo(v IndexInfo) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptIndexInfo) Get() (v IndexInfo, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptIndexInfo) Or(d IndexInfo) IndexInfo {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMigrateProps returns new OptMigrateProps with value set to v.
func NewOptMigrateProps(v MigrateProps) OptMigrateProps {
	return OptMigrateProps{
		Value: v,
		Set:   true,
	}
}

// OptMigrateProps is optional MigrateProps.
type OptMigrateProps struct {
	Value MigrateProps
	Set   bool
}

// IsSet returns true if OptMigrateProps was set.
func (o OptMigrateProps) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMigrateProps) Reset() {
	var v MigrateProps
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMigrateProps) SetTo(v MigrateProps) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMigrateProps) Get() (v MigrateProps, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMigrateProps) Or(d MigrateProps) MigrateProps {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTableDef returns new OptTableDef with value set to v.
func NewOptTableDef(v TableDef) OptTableDef {
	return OptTableDef{
		Value: v,
		Set:   true,
	}
}

// OptTableDef is optional TableDef.
type OptTableDef struct {
	Value TableDef
	Set   bool
}

// IsSet returns true if OptTableDef was set.
func (o OptTableDef) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTableDef) Reset() {
	var v TableDef
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTableDef) SetTo(v TableDef) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTableDef) Get() (v TableDef, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTableDef) Or(d TableDef) TableDef {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTableUpdateProps returns new OptTableUpdateProps with value set to v.
func NewOptTableUpdateProps(v TableUpdateProps) OptTableUpdateProps {
	return OptTableUpdateProps{
		Value: v,
		Set:   true,
	}
}

// OptTableUpdateProps is optional TableUpdateProps.
type OptTableUpdateProps struct {
	Value TableUpdateProps
	Set   bool
}

// IsSet returns true if OptTableUpdateProps was set.
func (o OptTableUpdateProps) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTableUpdateProps) Reset() {
	var v TableUpdateProps
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTableUpdateProps) SetTo(v TableUpdateProps) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTableUpdateProps) Get() (v TableUpdateProps, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTableUpdateProps) Or(d TableUpdateProps) TableUpdateProps {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// An RFC 7807 Problem Details object. Every non 2xx response carries one. The `code` member mirrors
// the last segment of `type` so clients can branch on a stable string without parsing the URI.
// Ref: #/components/schemas/Problem
type Problem struct {
	// A stable URN identifying the problem kind, for example `urn:rad:problem:conflict`.
	Type string `json:"type"`
	// A short, human readable summary of the problem kind.
	Title string `json:"title"`
	// The HTTP status code, repeated in the body for convenience.
	Status int `json:"status"`
	// A human readable explanation specific to this occurrence.
	Detail OptString `json:"detail"`
	// The machine readable class. One of `invalid` for a malformed or rejected request, `execution_failed`
	// for a valid query that failed on the data it met (division by zero, a violated cardinality
	// assertion), `not_found`, `conflict` for a lost optimistic race (an immediate retry may win —
	// constraint violations are `invalid`, since retrying them cannot help), or `internal`.
	Code ProblemCode `json:"code"`
	// The stable, fine-grained reason within the `code` class — for example `unknown_table`,
	// `division_by_zero`, or `mutation_target_not_found`. Reasons accumulate over time while the five
	// codes stay fixed; a client may switch on `reason` for precise handling, or fall back to `code`. When
	// the server did not name a specific reason it equals `code` (the class catch-all).
	Reason string `json:"reason"`
}

// GetType returns the value of Type.
func (s *Problem) GetType() string {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *Problem) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Problem) GetStatus() int {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *Problem) GetDetail() OptString {
	return s.Detail
}

// GetCode returns the value of Code.
func (s *Problem) GetCode() ProblemCode {
	return s.Code
}

// GetReason returns the value of Reason.
func (s *Problem) GetReason() string {
	return s.Reason
}

// SetType sets the value of Type.
func (s *Problem) SetType(val string) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *Problem) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Problem) SetStatus(val int) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *Problem) SetDetail(val OptString) {
	s.Detail = val
}

// SetCode sets the value of Code.
func (s *Problem) SetCode(val ProblemCode) {
	s.Code = val
}

// SetReason sets the value of Reason.
func (s *Problem) SetReason(val string) {
	s.Reason = val
}

func (*Problem) schemaMigrateRes() {}

// The machine readable class. One of `invalid` for a malformed or rejected request, `execution_failed`
// for a valid query that failed on the data it met (division by zero, a violated cardinality
// assertion), `not_found`, `conflict` for a lost optimistic race (an immediate retry may win —
// constraint violations are `invalid`, since retrying them cannot help), or `internal`.
type ProblemCode string

const (
	ProblemCodeInvalid         ProblemCode = "invalid"
	ProblemCodeExecutionFailed ProblemCode = "execution_failed"
	ProblemCodeNotFound        ProblemCode = "not_found"
	ProblemCodeConflict        ProblemCode = "conflict"
	ProblemCodeInternal        ProblemCode = "internal"
)

// AllValues returns all ProblemCode values.
func (ProblemCode) AllValues() []ProblemCode {
	return []ProblemCode{
		ProblemCodeInvalid,
		ProblemCodeExecutionFailed,
		ProblemCodeNotFound,
		ProblemCodeConflict,
		ProblemCodeInternal,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ProblemCode) MarshalText() ([]byte, error) {
	switch s {
	case ProblemCodeInvalid:
		return []byte(s), nil
	case ProblemCodeExecutionFailed:
		return []byte(s), nil
	case ProblemCodeNotFound:
		return []byte(s), nil
	case ProblemCodeConflict:
		return []byte(s), nil
	case ProblemCodeInternal:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ProblemCode) UnmarshalText(data []byte) error {
	switch ProblemCode(data) {
	case ProblemCodeInvalid:
		*s = ProblemCodeInvalid
		return nil
	case ProblemCodeExecutionFailed:
		*s = ProblemCodeExecutionFailed
		return nil
	case ProblemCodeNotFound:
		*s = ProblemCodeNotFound
		return nil
	case ProblemCodeConflict:
		*s = ProblemCodeConflict
		return nil
	case ProblemCodeInternal:
		*s = ProblemCodeInternal
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type Program jx.Raw

// The result of a program: the declared result statement's datum (shaped exactly as its LIR root
// materialises, as in `QueryResult`), plus a per-statement summary in execution order.
// Ref: #/components/schemas/ProgramResult
type ProgramResult struct {
	Result     Value             `json:"result"`
	Statements []StatementResult `json:"statements"`
	// Present only when the request set `show-plan`. Free-form JSON: the query plan for each statement —
	// the physical plan and the planner's access-path decisions, plus a rendered text form. Transport
	// observability metadata, not part of the LIR/PIR IR; its structure is deliberately unspecified here
	// and evolves with the planner.
	Plan Value `json:"plan"`
}

// GetResult returns the value of Result.
func (s *ProgramResult) GetResult() Value {
	return s.Result
}

// GetStatements returns the value of Statements.
func (s *ProgramResult) GetStatements() []StatementResult {
	return s.Statements
}

// GetPlan returns the value of Plan.
func (s *ProgramResult) GetPlan() Value {
	return s.Plan
}

// SetResult sets the value of Result.
func (s *ProgramResult) SetResult(val Value) {
	s.Result = val
}

// SetStatements sets the value of Statements.
func (s *ProgramResult) SetStatements(val []StatementResult) {
	s.Statements = val
}

// SetPlan sets the value of Plan.
func (s *ProgramResult) SetPlan(val Value) {
	s.Plan = val
}

func (*ProgramResult) executeRes() {}

// One statement's lightweight outcome.
// Ref: #/components/schemas/StatementResult
type StatementResult struct {
	Name string `json:"name"`
	// The number of rows the statement produced, created, updated, or deleted.
	Affected int `json:"affected"`
}

// GetName returns the value of Name.
func (s *StatementResult) GetName() string {
	return s.Name
}

// GetAffected returns the value of Affected.
func (s *StatementResult) GetAffected() int {
	return s.Affected
}

// SetName sets the value of Name.
func (s *StatementResult) SetName(val string) {
	s.Name = val
}

// SetAffected sets the value of Affected.
func (s *StatementResult) SetAffected(val int) {
	s.Affected = val
}

type TableCreateConflict Problem

func (*TableCreateConflict) tableCreateRes() {}

type TableCreateUnprocessableEntity Problem

func (*TableCreateUnprocessableEntity) tableCreateRes() {}

// A new table's definition: exactly what a `schema.rad` entry expresses, as JSON. Column types are
// `text`, `int64`, `float64`, or `bool`; the primary key is required and its columns must not be
// nullable.
// Ref: #/components/schemas/TableDef
type TableDef struct {
	Name        string           `json:"name"`
	Columns     []ColumnInfo     `json:"columns"`
	PrimaryKey  []string         `json:"primary_key"`
	Indexes     []IndexInfo      `json:"indexes"`
	ForeignKeys []ForeignKeyInfo `json:"foreign_keys"`
}

// GetName returns the value of Name.
func (s *TableDef) GetName() string {
	return s.Name
}

// GetColumns returns the value of Columns.
func (s *TableDef) GetColumns() []ColumnInfo {
	return s.Columns
}

// GetPrimaryKey returns the value of PrimaryKey.
func (s *TableDef) GetPrimaryKey() []string {
	return s.PrimaryKey
}

// GetIndexes returns the value of Indexes.
func (s *TableDef) GetIndexes() []IndexInfo {
	return s.Indexes
}

// GetForeignKeys returns the value of ForeignKeys.
func (s *TableDef) GetForeignKeys() []ForeignKeyInfo {
	return s.ForeignKeys
}

// SetName sets the value of Name.
func (s *TableDef) SetName(val string) {
	s.Name = val
}

// SetColumns sets the value of Columns.
func (s *TableDef) SetColumns(val []ColumnInfo) {
	s.Columns = val
}

// SetPrimaryKey sets the value of PrimaryKey.
func (s *TableDef) SetPrimaryKey(val []string) {
	s.PrimaryKey = val
}

// SetIndexes sets the value of Indexes.
func (s *TableDef) SetIndexes(val []IndexInfo) {
	s.Indexes = val
}

// SetForeignKeys sets the value of ForeignKeys.
func (s *TableDef) SetForeignKeys(val []ForeignKeyInfo) {
	s.ForeignKeys = val
}

type TableDeleteConflict Problem

func (*TableDeleteConflict) tableDeleteRes() {}

type TableDeleteUnprocessableEntity Problem

func (*TableDeleteUnprocessableEntity) tableDeleteRes() {}

// One table's definition, as reported by introspection.
// Ref: #/components/schemas/TableInfo
type TableInfo struct {
	Name    string       `json:"name"`
	Columns []ColumnInfo `json:"columns"`
	// The column names that make up the primary key, in order.
	PrimaryKey  []string         `json:"primary_key"`
	Indexes     []IndexInfo      `json:"indexes"`
	ForeignKeys []ForeignKeyInfo `json:"foreign_keys"`
}

// GetName returns the value of Name.
func (s *TableInfo) GetName() string {
	return s.Name
}

// GetColumns returns the value of Columns.
func (s *TableInfo) GetColumns() []ColumnInfo {
	return s.Columns
}

// GetPrimaryKey returns the value of PrimaryKey.
func (s *TableInfo) GetPrimaryKey() []string {
	return s.PrimaryKey
}

// GetIndexes returns the value of Indexes.
func (s *TableInfo) GetIndexes() []IndexInfo {
	return s.Indexes
}

// GetForeignKeys returns the value of ForeignKeys.
func (s *TableInfo) GetForeignKeys() []ForeignKeyInfo {
	return s.ForeignKeys
}

// SetName sets the value of Name.
func (s *TableInfo) SetName(val string) {
	s.Name = val
}

// SetColumns sets the value of Columns.
func (s *TableInfo) SetColumns(val []ColumnInfo) {
	s.Columns = val
}

// SetPrimaryKey sets the value of PrimaryKey.
func (s *TableInfo) SetPrimaryKey(val []string) {
	s.PrimaryKey = val
}

// SetIndexes sets the value of Indexes.
func (s *TableInfo) SetIndexes(val []IndexInfo) {
	s.Indexes = val
}

// SetForeignKeys sets the value of ForeignKeys.
func (s *TableInfo) SetForeignKeys(val []ForeignKeyInfo) {
	s.ForeignKeys = val
}

func (*TableInfo) columnCreateRes() {}
func (*TableInfo) columnDeleteRes() {}
func (*TableInfo) columnUpdateRes() {}
func (*TableInfo) indexCreateRes()  {}
func (*TableInfo) indexDeleteRes()  {}
func (*TableInfo) tableCreateRes()  {}
func (*TableInfo) tableUpdateRes()  {}

// The set of tables defined in the database.
// Ref: #/components/schemas/TableList
type TableList struct {
	Tables []TableInfo `json:"tables"`
}

// GetTables returns the value of Tables.
func (s *TableList) GetTables() []TableInfo {
	return s.Tables
}

// SetTables sets the value of Tables.
func (s *TableList) SetTables(val []TableInfo) {
	s.Tables = val
}

type TableUpdateConflict Problem

func (*TableUpdateConflict) tableUpdateRes() {}

// The table properties to update.
// Ref: #/components/schemas/TableUpdateProps
type TableUpdateProps struct {
	// The table's new name.
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *TableUpdateProps) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *TableUpdateProps) SetName(val string) {
	s.Name = val
}

type TableUpdateUnprocessableEntity Problem

func (*TableUpdateUnprocessableEntity) tableUpdateRes() {}

type Value jx.Raw
