// GENERATED by keyform from protocol/storage.keyform. Do not edit.
// Regenerate with `task generate:storage`.

//! Identity of the durable storage format this build reads and writes.

pub const STORAGE_FORMAT_NAME: &str = "storage";
pub const STORAGE_FORMAT_VERSION: u32 = 1;
/// SHA-256 of the normative specification text.
pub const STORAGE_SPEC_SHA256: &str =
    "bf2d26bca5d231c10aed1873060770352962ad7b568a28fcd2cb4f7305a47d14";
