// Package typescript is the TypeScript client generator. The emitted file is
// self-contained — a small fetch-based runtime plus typed models, table
// handles, query builders, and transactions — with zero dependencies, usable
// from Node, Bun, Deno, and browsers.
//
// Design choices:
//   - Property names mirror the wire exactly (snake_case column names, the
//     include "as" names): records need zero runtime mapping.
//   - Methods are camelCase (statusEq, orderByCreatedAtDesc, includeTasks).
//   - int64 columns are TypeScript numbers; values beyond 2^53 lose
//     precision in JSON.parse — acceptable for the POC and noted in the
//     generated header.
//   - A Patch field set to null clears the column (maps onto the wire's
//     clear list); undefined leaves it untouched.
package typescript

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/Southclaws/rad/rad/codegen"
)

func init() { codegen.Register("ts", generator{}) }

// generator is the registered TypeScript Generator.
type generator struct{}

// Generate emits the TypeScript client for the model.
func (generator) Generate(m *codegen.Model, opts codegen.Options) ([]codegen.GeneratedFile, error) {
	var b bytes.Buffer
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	emitTSHeader(p, opts.SchemaVersion, opts.SchemaHash, opts.SchemaSource)
	for _, t := range m.Tables {
		emitTSModel(p, t)
		emitTSTable(p, t)
		emitTSQuery(p, t)
		emitTSInclude(p, t)
	}
	emitTSClient(p, m)
	return []codegen.GeneratedFile{{Path: codegen.TypeScriptClientFilename, Content: b.Bytes()}}, nil
}

func tsType(goType string) string {
	switch goType {
	case "string":
		return "string"
	case "int64", "float64":
		return "number"
	case "bool":
		return "boolean"
	}
	return "unknown"
}

// lirScalar maps a column's Go type to its LIR scalar-type name, which a
// literal Value must carry — TypeScript collapses int64 and float64 to one
// `number`, so the generator supplies the distinction the runtime cannot.
func lirScalar(goType string) string {
	switch goType {
	case "string":
		return "text"
	case "int64":
		return "int64"
	case "float64":
		return "float64"
	case "bool":
		return "bool"
	}
	return "text"
}

// camel converts snake_case to lowerCamelCase: user_id -> userId.
func camel(s string) string {
	parts := strings.Split(s, "_")
	out := parts[0]
	for _, p := range parts[1:] {
		if p == "" {
			continue
		}
		out += strings.ToUpper(p[:1]) + p[1:]
	}
	return out
}

// upperCamel converts snake_case to UpperCamelCase.
func upperCamel(s string) string {
	c := camel(s)
	if c == "" {
		return c
	}
	return strings.ToUpper(c[:1]) + c[1:]
}

func emitTSHeader(p func(string, ...any), schemaVersion uint64, schemaHash string, schemaSrc []byte) {
	p("// Code generated by rad generate. DO NOT EDIT.")
	p("//")
	p("// Typed TypeScript client for a Rad database, speaking the rad:// wire")
	p("// protocol over fetch. Zero dependencies; works in Node 18+, Bun, Deno,")
	p("// and browsers. No SQL anywhere — queries compile to Rad's LIR on the")
	p("// wire. Note: int64 columns decode as JavaScript numbers; values beyond")
	p("// 2^53 lose precision.")
	p("")
	p("export const schemaVersion = %d;", schemaVersion)
	p("export const schemaHash = %q;", schemaHash)
	p("export const rawSchema = %s;", tsBacktickString(string(schemaSrc)))
	p("")
	// Runtime.
	p(`// runtime

export interface Problem {
  type: string;
  title: string;
  status: number;
  detail?: string;
  code: string;
  reason: string;
}

/** A non-2xx response from the server (RFC 7807 Problem Details). */
export class RadError extends Error {
  problem: Problem;
  constructor(problem: Problem) {
    super("rad: " + (problem.detail ?? problem.title) + " (" + problem.code + ", http " + problem.status + ")");
    this.name = "RadError";
    this.problem = problem;
  }
}

/** True when err is an optimistic transaction conflict — retry the tx. */
export function isConflict(err: unknown): boolean {
  return err instanceof RadError && err.problem.code === "conflict";
}

export type Scalar = string | number | boolean | null;

/** A self-describing literal scalar: its type names the scalar kind and an
 * absent value is a typed NULL. Numbers travel as strings for lossless int64
 * precision; a bool is a native JSON boolean. */
export type Value =
  | { type: "text"; value?: string }
  | { type: "int64"; value?: string }
  | { type: "float64"; value?: string }
  | { type: "bool"; value?: boolean };

/** A rows-cell payload, decoded against its column's declared type: null is a
 * NULL, otherwise the lossless string form (a bool is "true"/"false"). */
export type Cell = string | null;

/** One typed datum computation. Crossings may produce rows or arrays. */
export interface Expr {
  kind: "lit" | "col" | "unary" | "binary" | "cast" | "exists" | "first" | "scalar" | "array";
  value?: Value;
  scope?: string;
  column?: string;
  op?: string;
  expr?: Expr;
  left?: Expr;
  right?: Expr;
  to?: string;
  node?: string;
}

/** One relation operator: a flat tagged union selected by kind. */
export interface Node {
  kind: "scan" | "filter" | "project" | "join" | "aggregate" | "order" | "slice" | "rows";
  table?: string;
  scope?: string;
  input?: string;
  left?: string;
  right?: string;
  join?: "inner" | "left";
  on?: Expr;
  predicate?: Expr;
  spread?: string[];
  fields?: Field[];
  groups?: GroupTerm[];
  aggs?: AggTerm[];
  terms?: OrderTerm[];
  offset?: number;
  limit?: number;
  columns?: { name: string; type: string; nullable?: boolean }[];
  rows?: Cell[][];
}

export interface Field {
  as: string;
  expr: Expr;
}

export interface GroupTerm {
  as?: string;
  expr: Expr;
}

export interface AggTerm {
  fn: "count" | "sum" | "avg" | "min" | "max";
  arg?: Expr;
  as: string;
}

export interface OrderTerm {
  expr: Expr;
  desc?: boolean;
}

/** LIR's single-consumer relation tree on the wire. */
export interface GraphQuery {
  nodes: Record<string, Node>;
  root: { node: string; cardinality: "many" | "first" | "exactly_one" | "scalar" };
}

type Rec = Record<string, unknown>;

/** Parses rad://host[:port] (or rads:// for HTTPS) into an http(s) base URL. */
export function parseRadUrl(url: string): string {
  const m = /^(rad|rads):\/\/([^/?#@]+?)(:\d+)?\/?$/.exec(url);
  if (!m) throw new Error("connection URI must be rad(s)://host[:port], got " + url);
  const scheme = m[1] === "rads" ? "https" : "http";
  return scheme + "://" + m[2] + (m[3] ?? ":7237");
}

class Rpc {
  private base: string;
  private fetchImpl: typeof fetch;
  private compatibility?: Promise<void>;
  constructor(base: string, fetchImpl?: typeof fetch) {
    this.base = base;
    this.fetchImpl = fetchImpl ?? fetch;
  }

  async req<T>(path: string, body?: unknown): Promise<T> {
    await this.ensureCompatible();
    return this.rawReq(path, body);
  }

  private async ensureCompatible(): Promise<void> {
    if (!this.compatibility) {
      this.compatibility = this.rawReq<void>("/schema/compatibility", {
        schema_version: schemaVersion,
        schema_hash: schemaHash,
      });
    }
    return this.compatibility;
  }

  private async rawReq<T>(path: string, body?: unknown): Promise<T> {
    const res = await this.fetchImpl(this.base + path, {
      method: body === undefined ? "GET" : "POST",
      headers: body === undefined ? undefined : { "Content-Type": "application/json" },
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    if (!res.ok) {
      let problem: Problem;
      try {
        problem = (await res.json()) as Problem;
      } catch {
        problem = { type: "urn:rad:problem:internal", title: res.statusText, status: res.status, code: "internal", reason: "internal" };
      }
      throw new RadError(problem);
    }
    const text = await res.text();
    return (text ? JSON.parse(text) : undefined) as T;
  }
}

interface View {
  query(q: GraphQuery): Promise<Rec[]>;
  get(table: string, key: Rec): Promise<Rec | null>;
  create(table: string, values: Rec): Promise<Rec>;
  update(table: string, key: Rec, set: Rec, clear: string[]): Promise<Rec | null>;
  del(table: string, key: Rec): Promise<boolean>;
}

// A column of a table, as reported by introspection — the types a create
// needs to build a typed rows relation.
interface ColumnInfo { name: string; type: string; nullable?: boolean }

// WireView is the data surface: every operation is one PIR program over
// /execute. A read is a query statement; a single-row write is a mutation
// statement whose input is a literal rows relation (create) or a scan
// projected to the target key/values (update, delete).
class WireView implements View {
  private rpc: Rpc;
  private schema?: Promise<Map<string, ColumnInfo[]>>;
  constructor(rpc: Rpc) {
    this.rpc = rpc;
  }

  private async columns(table: string): Promise<ColumnInfo[]> {
    if (!this.schema) {
      this.schema = this.rpc.req<{ tables: { name: string; columns: ColumnInfo[] }[] }>("/tables").then((res) => {
        const m = new Map<string, ColumnInfo[]>();
        for (const t of res.tables) m.set(t.name, t.columns);
        return m;
      });
    }
    const cols = (await this.schema).get(table);
    if (!cols) throw new Error("unknown table " + table);
    return cols;
  }

  private async run(stmt: Statement): Promise<unknown> {
    const res = await this.rpc.req<{ result: unknown }>("/execute", { statements: [stmt] });
    return res.result;
  }

  private records(result: unknown): Rec[] {
    if (result === null || result === undefined) return [];
    if (Array.isArray(result)) return result as Rec[];
    return [result as Rec];
  }

  async query(q: GraphQuery): Promise<Rec[]> {
    return this.records(await this.run({ name: "q", kind: "query", relation: q }));
  }
  // keyPreds builds the equality predicates identifying a row by key, each
  // literal typed from the catalog so it is a self-describing Value.
  private async keyPreds(table: string, key: Rec): Promise<Expr[]> {
    const types = new Map((await this.columns(table)).map((c) => [c.name, c]));
    return Object.entries(key).map(([column, value]): Expr => {
      const c = types.get(column);
      if (!c) throw new Error("table " + table + " has no column " + column);
      return eq(col("s", column), lit(toValue(c.type, value as Scalar)));
    });
  }

  async get(table: string, key: Rec): Promise<Rec | null> {
    const preds = await this.keyPreds(table, key);
    const recs = this.records(await this.run({ name: "get", kind: "query", relation: {
      nodes: {
        s: { kind: "scan", table, scope: "s" },
        keyed: { kind: "filter", input: "s", predicate: andAll(preds) },
        one: { kind: "slice", input: "keyed", limit: 1 },
      },
      root: { node: "one", cardinality: "first" },
    } }));
    return recs.length ? recs[0] : null;
  }
  async create(table: string, values: Rec): Promise<Rec> {
    const cols = await this.columns(table);
    const types = new Map(cols.map((c) => [c.name, c]));
    const names = Object.keys(values).sort();
    const relation: GraphQuery = {
      nodes: {
        r: {
          kind: "rows", scope: "r",
          columns: names.map((n) => {
            const c = types.get(n);
            if (!c) throw new Error("table " + table + " has no column " + n);
            return { name: n, type: c.type, nullable: c.nullable ?? false };
          }),
          rows: [names.map((n) => toCell(types.get(n)!.type, values[n] as Scalar))],
        },
      },
      root: { node: "r", cardinality: "many" },
    };
    const recs = this.records(await this.run({ name: "create", kind: "create", table, relation }));
    return recs[0];
  }
  async update(table: string, key: Rec, set: Rec, clear: string[]): Promise<Rec | null> {
    // Identify by primary key and assign via a one-row relation typed from
    // the catalog — a cleared column is a typed NULL, which a bare literal
    // cannot express. A missing key is a not-found error, mapped to null to
    // keep the point-update contract.
    const cols = await this.columns(table);
    const types = new Map(cols.map((c) => [c.name, c]));
    const relCols: { name: string; type: string; nullable: boolean }[] = [];
    const row: Cell[] = [];
    const add = (name: string, val: Scalar) => {
      const c = types.get(name);
      if (!c) throw new Error("table " + table + " has no column " + name);
      relCols.push({ name, type: c.type, nullable: c.nullable ?? false });
      row.push(toCell(c.type, val));
    };
    for (const [k, v] of Object.entries(key)) add(k, v as Scalar);
    for (const [k, v] of Object.entries(set)) add(k, v as Scalar);
    for (const k of clear) add(k, null);
    const relation: GraphQuery = {
      nodes: { r: { kind: "rows", scope: "r", columns: relCols, rows: [row] } },
      root: { node: "r", cardinality: "many" },
    };
    try {
      const recs = this.records(await this.run({ name: "update", kind: "update", table, relation }));
      return recs.length ? recs[0] : null;
    } catch (err) {
      if (err instanceof RadError && err.problem.detail?.includes("target not found")) return null;
      throw err;
    }
  }
  async del(table: string, key: Rec): Promise<boolean> {
    const preds = await this.keyPreds(table, key);
    const fields = Object.keys(key).map((k) => ({ as: k, expr: col("s", k) }));
    const relation = this.keyedProjection(table, preds, fields);
    const res = await this.rpc.req<{ statements: { affected: number }[] }>("/execute", {
      statements: [{ name: "delete", kind: "delete", table, relation }],
    });
    return res.statements.length === 1 && res.statements[0].affected > 0;
  }

  // keyedProjection scans a table, filters to the key row, and projects the
  // given fields — the identify-by-key input for delete.
  private keyedProjection(table: string, preds: Expr[], fields: { as: string; expr: Expr }[]): GraphQuery {
    return {
      nodes: {
        s: { kind: "scan", table, scope: "s" },
        keyed: { kind: "filter", input: "s", predicate: andAll(preds) },
        p: { kind: "project", input: "keyed", fields },
      },
      root: { node: "p", cardinality: "many" },
    };
  }
}

// Statement is one PIR statement: a kind, a name, an LIR relation, and — for
// mutations — a target table.
interface Statement { name: string; kind: string; relation: GraphQuery; table?: string }

/** Splits a patch into wire set/clear: null values clear the column. */
function splitPatch(patch: Rec): { set: Rec; clear: string[] } {
  const set: Rec = {};
  const clear: string[] = [];
  for (const [k, v] of Object.entries(patch)) {
    if (v === undefined) continue;
    if (v === null) clear.push(k);
    else set[k] = v;
  }
  return { set, clear };
}

// -
// graph assembly
// -

function col(scope: string, column: string): Expr {
  return { kind: "col", scope, column };
}
function lit(value: Value): Expr {
  return { kind: "lit", value };
}

// toValue builds a self-describing literal of the given scalar type. null is a
// typed NULL; numbers serialise as strings so int64 keeps full precision (an
// int64 column truncates any fractional part).
function toValue(type: string, v: Scalar): Value {
  if (v === null) {
    switch (type) {
      case "text": return { type: "text" };
      case "int64": return { type: "int64" };
      case "float64": return { type: "float64" };
      case "bool": return { type: "bool" };
    }
    throw new Error("unknown scalar type " + type);
  }
  switch (type) {
    case "text": return { type: "text", value: String(v) };
    case "int64": return { type: "int64", value: typeof v === "number" ? String(Math.trunc(v)) : String(v) };
    case "float64": return { type: "float64", value: String(v) };
    case "bool": return { type: "bool", value: Boolean(v) };
  }
  throw new Error("unknown scalar type " + type);
}

// toCell renders a rows cell against its column's type: null stays NULL, a bool
// is "true"/"false", and everything else is its lossless string form.
function toCell(type: string, v: Scalar): Cell {
  if (v === null) return null;
  switch (type) {
    case "bool": return v ? "true" : "false";
    case "int64": return typeof v === "number" ? String(Math.trunc(v)) : String(v);
    default: return String(v);
  }
}
function eq(left: Expr, right: Expr): Expr {
  return { kind: "binary", op: "eq", left, right };
}
function bin(op: string, left: Expr, right: Expr): Expr {
  return { kind: "binary", op, left, right };
}
function un(op: string, expr: Expr): Expr {
  return { kind: "unary", op, expr };
}
function andAll(preds: Expr[]): Expr | undefined {
  let out: Expr | undefined;
  for (const p of preds) out = out ? bin("and", out, p) : p;
  return out;
}

/** A fluent builder's accumulated state; assemble compiles it to the graph. */
interface QuerySpec {
  table: string;
  filters: Expr[];
  orders: OrderTerm[];
  offset?: number;
  limit?: number;
  includes: IncludeSpec[];
  aggs?: AggTerm[];
}

interface IncludeSpec {
  table: string;
  pairs: [string, string][]; // scanned-side column = outer-scope column
  as: string;
  kind: "first" | "array" | "fold";
  filters: Expr[];
  orders: OrderTerm[];
  limit?: number;
  nested: IncludeSpec[];
  aggs?: AggTerm[];
}

/** Fills unscoped column references with the relation's scope. */
function scopeExpr(e: Expr, scope: string): Expr {
  const c: Expr = { ...e };
  if (c.kind === "col" && !c.scope) c.scope = scope;
  if (c.expr) c.expr = scopeExpr(c.expr, scope);
  if (c.left) c.left = scopeExpr(c.left, scope);
  if (c.right) c.right = scopeExpr(c.right, scope);
  return c;
}

function scopeAggs(aggs: AggTerm[], scope: string): AggTerm[] {
  return aggs.map((a) => ({ fn: a.fn, arg: a.arg ? scopeExpr(a.arg, scope) : undefined, as: a.as }));
}

/** Compiles a spec into a grouped fold: one row per distinct value of
 * groupCol, counted, ordered by the group key — the aggregate binds an
 * output scope so the ordering can address its key. */
function assembleGrouped(s: QuerySpec, groupCol: string): GraphQuery {
  const nodes: Record<string, Node> = {};
  let n = 0;
  const next = () => "n" + n++;
  const scope = next();
  nodes[scope] = { kind: "scan", table: s.table, scope };
  let last = scope;
  const pred = andAll(s.filters.map((f) => scopeExpr(f, scope)));
  if (pred) {
    const id = next();
    nodes[id] = { kind: "filter", input: last, predicate: pred };
    last = id;
  }
  const agg = next();
  nodes[agg] = {
    kind: "aggregate", input: last, scope: agg,
    groups: [{ expr: col(scope, groupCol) }],
    aggs: [{ fn: "count", as: "count" }],
  };
  const ord = next();
  nodes[ord] = { kind: "order", input: agg, terms: [{ expr: col(agg, groupCol) }] };
  return { nodes, root: { node: ord, cardinality: "many" } };
}

/** Compiles a spec into the wire graph with deterministic node ids: a
 * preorder walk, each scan's id doubling as its scope label. */
function assemble(s: QuerySpec): GraphQuery {
  const nodes: Record<string, Node> = {};
  let n = 0;
  const next = () => "n" + n++;

  const chain = (
    table: string, pairs: [string, string][], outerScope: string,
    filters: Expr[], orders: OrderTerm[], offset?: number, limit?: number,
  ): [string, string] => {
    const scope = next();
    nodes[scope] = { kind: "scan", table, scope };
    let last = scope;
    const preds = pairs.map(([local, outer]) => eq(col(scope, local), col(outerScope, outer)));
    for (const f of filters) preds.push(scopeExpr(f, scope));
    const pred = andAll(preds);
    if (pred) {
      const id = next();
      nodes[id] = { kind: "filter", input: last, predicate: pred };
      last = id;
    }
    if (orders.length) {
      const id = next();
      nodes[id] = { kind: "order", input: last, terms: orders.map((t) => ({ expr: scopeExpr(t.expr, scope), desc: t.desc })) };
      last = id;
    }
    if ((offset ?? 0) > 0 || limit !== undefined) {
      const id = next();
      const node: Node = { kind: "slice", input: last };
      if ((offset ?? 0) > 0) node.offset = offset;
      if (limit !== undefined) node.limit = limit;
      nodes[id] = node;
      last = id;
    }
    return [last, scope];
  };

  const include = (inc: IncludeSpec, outerScope: string): Field => {
    if (inc.kind === "fold") {
      const [last, scope] = chain(inc.table, inc.pairs, outerScope, inc.filters, []);
      const id = next();
      nodes[id] = { kind: "aggregate", input: last, aggs: scopeAggs(inc.aggs ?? [], scope) };
      return { as: inc.as, expr: { kind: "first", node: id } };
    }
    let [last, scope] = chain(inc.table, inc.pairs, outerScope, inc.filters, inc.orders, 0, inc.limit);
    if (inc.nested.length) {
      const id = next();
      nodes[id] = { kind: "project", input: last, spread: [scope], fields: inc.nested.map((x) => include(x, scope)) };
      last = id;
    }
    return { as: inc.as, expr: { kind: inc.kind, node: last } };
  };

  let [last, scope] = chain(s.table, [], "", s.filters, s.orders, s.offset, s.limit);
  if (s.aggs && s.aggs.length) {
    const id = next();
    nodes[id] = { kind: "aggregate", input: last, aggs: scopeAggs(s.aggs, scope) };
		return { nodes, root: { node: id, cardinality: "exactly_one" } };
  }
  if (s.includes.length) {
    const id = next();
    nodes[id] = { kind: "project", input: last, spread: [scope], fields: s.includes.map((x) => include(x, scope)) };
    last = id;
  }
  return { nodes, root: { node: last, cardinality: "many" } };
}`)
	p("")
}

func emitTSModel(p func(string, ...any), t *codegen.Table) {
	p("// %s", t.Name)
	p("")
	p("/** One row of %q. Relation fields are present only when included. */", t.Name)
	p("export interface %s {", t.Model)
	for _, c := range t.Cols {
		if c.Nullable {
			p("  %s: %s | null;", c.Name, tsType(c.GoType))
		} else {
			p("  %s: %s;", c.Name, tsType(c.GoType))
		}
	}
	for _, r := range t.Forward {
		p("  %s?: %s | null;", r.As, r.Target.Model)
	}
	for _, r := range t.Reverse {
		p("  %s?: %s[];", r.As, r.Target.Model)
	}
	p("}")
	p("")
	p("/** Input to create; omitted optional fields defer to defaults or NULL. */")
	p("export interface %sCreate {", t.Model)
	for _, c := range t.Cols {
		switch {
		case c.Nullable:
			p("  %s?: %s | null;", c.Name, tsType(c.GoType))
		case c.HasDef:
			p("  %s?: %s;", c.Name, tsType(c.GoType))
		default:
			p("  %s: %s;", c.Name, tsType(c.GoType))
		}
	}
	p("}")
	p("")
	p("/** Input to update: undefined leaves a column untouched; null clears a")
	p(" * nullable column. */")
	p("export interface %sPatch {", t.Model)
	for _, c := range t.Cols {
		if c.IsPK {
			continue
		}
		if c.Nullable {
			p("  %s?: %s | null;", c.Name, tsType(c.GoType))
		} else {
			p("  %s?: %s;", c.Name, tsType(c.GoType))
		}
	}
	p("}")
	p("")
}

// tsPKParams renders "id: string" or "teamId: string, userId: string".
func tsPKParams(t *codegen.Table) string {
	out := ""
	for i, c := range t.PK {
		if i > 0 {
			out += ", "
		}
		out += camel(c.Name) + ": " + tsType(c.GoType)
	}
	return out
}

func tsPKKey(t *codegen.Table) string {
	out := "{ "
	for i, c := range t.PK {
		if i > 0 {
			out += ", "
		}
		out += fmt.Sprintf("%s: %s", c.Name, camel(c.Name))
	}
	return out + " }"
}

func emitTSTable(p func(string, ...any), t *codegen.Table) {
	p("export class %sTable {", t.Model)
	p("  private v: View;")
	p("  constructor(v: View) {")
	p("    this.v = v;")
	p("  }")
	p("")
	p("  async create(input: %sCreate): Promise<%s> {", t.Model, t.Model)
	p("    return (await this.v.create(%q, input as unknown as Rec)) as unknown as %s;", t.Name, t.Model)
	p("  }")
	p("")
	p("  async get(%s): Promise<%s | null> {", tsPKParams(t), t.Model)
	p("    return (await this.v.get(%q, %s)) as %s | null;", t.Name, tsPKKey(t), t.Model)
	p("  }")
	p("")
	p("  async update(%s, patch: %sPatch): Promise<%s | null> {", tsPKParams(t), t.Model, t.Model)
	p("    const { set, clear } = splitPatch(patch as unknown as Rec);")
	p("    return (await this.v.update(%q, %s, set, clear)) as %s | null;", t.Name, tsPKKey(t), t.Model)
	p("  }")
	p("")
	p("  async delete(%s): Promise<boolean> {", tsPKParams(t))
	p("    return this.v.del(%q, %s);", t.Name, tsPKKey(t))
	p("  }")
	for _, uq := range t.Uniques {
		name := "by"
		params := ""
		var filters []string
		for i, c := range uq {
			name += upperCamel(c.Name)
			if i > 0 {
				params += ", "
			}
			params += camel(c.Name) + ": " + tsType(c.GoType)
			filters = append(filters, fmt.Sprintf("eq(col(\"\", %q), lit(toValue(%q, %s)))", c.Name, lirScalar(c.GoType), camel(c.Name)))
		}
		p("")
		p("  /** Finds the row by the unique index on (%s). */", codegen.UqCols(uq))
		p("  async %s(%s): Promise<%s | null> {", name, params, t.Model)
		p("    const recs = await this.v.query(assemble({ table: %q, filters: [%s], orders: %s, includes: [], limit: 1 }));", t.Name, strings.Join(filters, ", "), tsDefaultOrderTerms(t))
		p("    return recs.length ? (recs[0] as unknown as %s) : null;", t.Model)
		p("  }")
	}
	p("")
	p("  query(): %sQuery {", t.Model)
	p("    return new %sQuery(this.v);", t.Model)
	p("  }")
	p("}")
	p("")
}

// emitTSFilterMethods writes the shared typed-predicate methods for query
// and include builders.
func emitTSFilterMethods(p func(string, ...any), t *codegen.Table) {
	for _, c := range t.Cols {
		m := camel(c.Name)
		ty := tsType(c.GoType)
		sc := lirScalar(c.GoType)
		p("  %sEq(v: %s): this { this.filters.push(bin(\"eq\", col(\"\", %q), lit(toValue(%q, v)))); return this; }", m, ty, c.Name, sc)
		p("  %sNe(v: %s): this { this.filters.push(bin(\"ne\", col(\"\", %q), lit(toValue(%q, v)))); return this; }", m, ty, c.Name, sc)
		if c.GoType != "bool" {
			for _, op := range []struct{ suffix, op string }{
				{"Lt", "lt"}, {"Lte", "lte"}, {"Gt", "gt"}, {"Gte", "gte"},
			} {
				p("  %s%s(v: %s): this { this.filters.push(bin(%q, col(\"\", %q), lit(toValue(%q, v)))); return this; }", m, op.suffix, ty, op.op, c.Name, sc)
			}
		}
		if c.Nullable {
			p("  %sNull(): this { this.filters.push(un(\"is_null\", col(\"\", %q))); return this; }", m, c.Name)
			p("  %sNotNull(): this { this.filters.push(un(\"is_not_null\", col(\"\", %q))); return this; }", m, c.Name)
		}
	}
}

func emitTSOrderMethods(p func(string, ...any), t *codegen.Table, orderTarget string) {
	for _, c := range t.Cols {
		m := upperCamel(c.Name)
		p("  orderBy%s(): this { %s.push({ expr: col(\"\", %q) }); return this; }", m, orderTarget, c.Name)
		p("  orderBy%sDesc(): this { %s.push({ expr: col(\"\", %q), desc: true }); return this; }", m, orderTarget, c.Name)
	}
}

func emitTSIncludeMethods(p func(string, ...any), t *codegen.Table, pushStmt string) {
	emit := func(r codegen.Rel, kind string) {
		p("  include%s(fn?: (b: %sInclude) => void): this {", upperCamel(r.As), r.Target.Model)
		p("    const b = new %sInclude(%q, %s, %q, %q);", r.Target.Model, r.Target.Name, tsPairs(r.Pairs), r.As, kind)
		p("    fn?.(b);")
		p("    %s(b.build());", pushStmt)
		p("    return this;")
		p("  }")
	}
	for _, r := range t.Forward {
		emit(r, "first")
	}
	for _, r := range t.Reverse {
		emit(r, "array")
	}
}

// tsPairs renders correlation pairs as a TS literal.
func tsPairs(pairs [][2]string) string {
	out := "["
	for i, pr := range pairs {
		if i > 0 {
			out += ", "
		}
		out += fmt.Sprintf("[%q, %q]", pr[0], pr[1])
	}
	return out + "]"
}

func emitTSQuery(p func(string, ...any), t *codegen.Table) {
	p("/** Fluent query builder for %q; conditions AND together. */", t.Name)
	p("export class %sQuery {", t.Model)
	p("  private filters: Expr[] = [];")
	p("  private spec: QuerySpec = { table: %q, filters: [], orders: [], includes: [] };", t.Name)
	p("  private v: View;")
	p("  constructor(v: View) {")
	p("    this.v = v;")
	p("    this.spec.filters = this.filters;")
	p("  }")
	p("")
	emitTSFilterMethods(p, t)
	p("")
	emitTSOrderMethods(p, t, "this.spec.orders")
	p("")
	p("  limit(n: number): this { this.spec.limit = n; return this; }")
	p("  offset(n: number): this { this.spec.offset = n; return this; }")
	p("")
	emitTSIncludeMethods(p, t, "this.spec.includes.push")
	p("")
	p("  async all(): Promise<%s[]> {", t.Model)
	// A many-root collection must carry an order — its rows are observable.
	// Default to the primary key when the caller gave none, matching the Go
	// client, so a bare .all() is deterministic rather than rejected.
	p("    if (!this.spec.orders.length) this.spec.orders = %s;", tsDefaultOrderTerms(t))
	p("    return (await this.v.query(assemble(this.spec))) as unknown as %s[];", t.Model)
	p("  }")
	p("")
	p("  async first(): Promise<%s | null> {", t.Model)
	p("    if (!this.spec.orders.length) this.spec.orders = %s;", tsDefaultOrderTerms(t))
	p("    this.spec.limit = 1;")
	p("    const rows = await this.all();")
	p("    return rows.length ? rows[0] : null;")
	p("  }")
	p("")
	emitTSAggregates(p, t)
	p("}")
	p("")
}

func tsDefaultOrderTerms(t *codegen.Table) string {
	terms := make([]string, len(t.PK))
	for i, c := range t.PK {
		terms[i] = fmt.Sprintf("{ expr: col(\"\", %q) }", c.Name)
	}
	return "[" + strings.Join(terms, ", ") + "]"
}

// emitTSAggregates writes the terminal fold methods. They reuse the builder's
// filter but not its ordering/pagination/includes (meaningless for a fold).
// count() is always a number; the rest return null when no rows matched.
func emitTSAggregates(p func(string, ...any), t *codegen.Table) {
	p("  private async fold(aggs: AggTerm[]): Promise<Rec> {")
	p("    const recs = await this.v.query(assemble({ table: this.spec.table, filters: this.filters, orders: [], includes: [], aggs }));")
	p("    return recs[0] ?? {};")
	p("  }")
	p("")
	p("  /** How many rows match (never null: 0 when none). */")
	p("  async count(): Promise<number> {")
	p("    const rec = await this.fold([{ fn: \"count\", as: \"v\" }]);")
	p("    return (rec[\"v\"] as number) ?? 0;")
	p("  }")

	fold := func(method, fn, col, ty, doc string) {
		p("  /** %s */", doc)
		p("  async %s(): Promise<%s | null> {", method, ty)
		p("    const rec = await this.fold([{ fn: %q, arg: col(\"\", %q), as: \"v\" }]);", fn, col)
		p("    return (rec[\"v\"] as %s | null) ?? null;", ty)
		p("  }")
	}
	for _, c := range t.Cols {
		m := upperCamel(c.Name)
		ty := tsType(c.GoType)
		if c.GoType == "int64" || c.GoType == "float64" {
			fold("sum"+m, "sum", c.Name, "number", fmt.Sprintf("Total of %q (null when no rows).", c.Name))
			fold("avg"+m, "avg", c.Name, "number", fmt.Sprintf("Average of %q (null when no rows).", c.Name))
		}
		fold("min"+m, "min", c.Name, ty, fmt.Sprintf("Smallest %q (null when no rows).", c.Name))
		fold("max"+m, "max", c.Name, ty, fmt.Sprintf("Largest %q (null when no rows).", c.Name))
	}

	for _, c := range t.Cols {
		m := upperCamel(c.Name)
		keyTy := tsType(c.GoType)
		if c.Nullable {
			keyTy += " | null"
		}
		p("  /** Counts matching rows per distinct %q, ordered by the group key. */", c.Name)
		p("  async countBy%s(): Promise<{ %s: %s; count: number }[]> {", m, camel(c.Name), keyTy)
		p("    const recs = await this.v.query(assembleGrouped({ table: this.spec.table, filters: this.filters, orders: [], includes: [] }, %q));", c.Name)
		p("    return recs as unknown as { %s: %s; count: number }[];", camel(c.Name), keyTy)
		p("  }")
	}
}

func emitTSInclude(p func(string, ...any), t *codegen.Table) {
	p("/** Refines an included %q fetch. */", t.Name)
	p("export class %sInclude {", t.Model)
	p("  private filters: Expr[] = [];")
	p("  private orders: OrderTerm[] = [];")
	p("  private nested: IncludeSpec[] = [];")
	p("  private max?: number;")
	p("  private table: string;")
	p("  private pairs: [string, string][];")
	p("  private as: string;")
	p("  private kind: \"first\" | \"array\";")
	p("  constructor(table: string, pairs: [string, string][], as_: string, kind: \"first\" | \"array\") {")
	p("    this.table = table;")
	p("    this.pairs = pairs;")
	p("    this.as = as_;")
	p("    this.kind = kind;")
	p("  }")
	p("")
	emitTSFilterMethods(p, t)
	p("")
	emitTSOrderMethods(p, t, "this.orders")
	p("")
	p("  limit(n: number): this { this.max = n; return this; }")
	p("")
	emitTSIncludeMethods(p, t, "this.nested.push")
	p("")
	p("  build(): IncludeSpec {")
	p("    return {")
	p("      table: this.table, pairs: this.pairs, as: this.as, kind: this.kind,")
	p("      filters: this.filters, orders: this.orders, limit: this.max,")
	p("      nested: this.nested,")
	p("    };")
	p("  }")
	p("}")
	p("")
}

func emitTSClient(p func(string, ...any), m *codegen.Model) {
	p("// client")
	p("")
	p("export class Client {")
	p("  private rpc: Rpc;")
	for _, t := range m.Tables {
		p("  readonly %s: %sTable;", camel(t.Name), t.Model)
	}
	p("")
	p("  /** Connects to a Rad server, e.g. new Client(\"rad://localhost\"). */")
	p("  constructor(url: string, fetchImpl?: typeof fetch) {")
	p("    this.rpc = new Rpc(parseRadUrl(url), fetchImpl);")
	p("    const view = new WireView(this.rpc);")
	for _, t := range m.Tables {
		p("    this.%s = new %sTable(view);", camel(t.Name), t.Model)
	}
	p("  }")
	p("")
	p("  /** Verifies the server is reachable. */")
	p("  async ping(): Promise<void> {")
	p("    await this.rpc.req(\"/health\");")
	p("  }")
	p("}")
	p("")
	p("/** Connects to a Rad server. */")
	p("export function connect(url: string, fetchImpl?: typeof fetch): Client {")
	p("  return new Client(url, fetchImpl);")
	p("}")
}

// tsBacktickString renders s as a TS template literal, escaping the few
// significant characters.
func tsBacktickString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "`", "\\`")
	s = strings.ReplaceAll(s, "${", "\\${")
	return "`" + s + "`"
}
